### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by pzolla** [jyapayne/Web2Executable#102]
Is there a way to activate the normal browser zoom functionality?

**Comment by jyapayne** [comment]
[Apparently not](https://github.com/nwjs/nw.js/issues/1818). What you'll have to do is listen to events and update the zoom level in javascript (see [here](https://github.com/nwjs/nw.js/wiki/window#windowzoomlevel)). I'm assuming you want ctrl-scroll functionality though. What mode of zooming are you referring to?

**Comment by pzolla** [comment]
I am referring to the zoom within the browser menu.  CTRL + and CRTL - for example.

Unfortunately, the browser based zoom does not work them same as manipulating the zoom level in JavaScript.  Or maybe more accurately, despite days of trying all various methods of getting zoom to work the same, I have been unsuccessful.  I can get it to zoom but never as nice and proportional as the browser.

While I have your attention - quick question #2 - I have Window Settings: Title filled in but it still says "Title" in the app.  Is there a trick I am missing?

**Comment by jyapayne** [comment]
Ah, that must be super frustrating. Unfortunately nw.js doesn't offer the zooming functionality, even though it should it theory.

As for your other question, the Title field will only take into effect if your index.html file's title tag is blank. In other words, it might be the title tag in your html file that still has "Title" as the title :)

**Comment by pzolla** [comment]
Thanks for info.  I will review the links above an give it another shot.
 
As for the title, I suspect that it exactly it.  If I recall that field has no tooltip.  This info may be a useful one.

 
Date: Fri, 20 Nov 2015 09:31:44 -0800

**Comment by jyapayne** [comment]
Any luck with zooming?

**Comment by pzolla** [comment]
Honestly, I have not had a chance to follow up yet but will report back in the next few weeks.
 
Date: Thu, 26 Nov 2015 18:20:18 -0800

**Comment by jyapayne** [comment]
Alright, no hurry :)

**Comment by pzolla** [comment]
I was finally successful in getting zoom to work the same way the Chrome browser does with CRTL + and CRTL -.  (CSS transforms and zoom do not work the same way as the browser zoom).

https://github.com/nwjs/nw.js/issues/2023

var zoomPercent = 150;
var win = require("nw.gui").Window.get();
win.zoomLevel = Math.log(zoomPercent/100) / Math.log(1.2);

I am hooking this to a counter form control but I assume you could tie it to keystrokes.  (I don't know how so I did not try).

I will test in Electron but I suspect it will work there as well.  (I have to use Electron for my final build because I need more control over the title bar.  But Web2Executable is great for dev).

**Comment by jyapayne** [comment]
Cool :) Sounds good! Thanks for updating the issue with the solution!
