### ISSUE TITLE
Excelente Programa (Web2Executable)

### ISSUE THREAD

**Issue by soycamiloypunto** [jyapayne/Web2Executable#104]
Quisiera saber si es posible usar el alpha de la última versión en pruebas de NWJS 0.13.0 en la descarga de NW dentro de Web2Executable

ya que no se puede usar esta última versión.

**Comment by jyapayne** [comment]
Al menos traductor Google su problema :) Yo no hablo español ! Si edita el archivo " nw- versions.txt " y poner " v0.13.0 - alfa6 " como la primera línea , podrás descargarlo cuando abre Web2Executable siguiente.

Esperemos que esto se traduce bien (estoy usando Google Translate) . Gracias a su para la presentación de la cuestión !

**Comment by soycamiloypunto** [comment]
Hello, I tried what you said, but not worked.
I added the first line in the "nw-versions" file and the program does not recognize.

copy of the file:


0.13.0-alpha6
0.12.2
0.12.1
0.12.0
0.12.0-rc1
0.12.0-alpha3
0.12.0-alpha2
0.12.0-alpha1
0.11.3
0.11.2
0.11.1
0.11.0
0.11.0-rc1
0.10.5
0.10.4
0.10.3
0.10.2
0.10.1
0.10.0
0.10.0-rc2
0.10.0-rc1
0.9.2
0.9.1
0.9.0
0.8.6
0.8.5
0.8.4
0.8.3
0.8.2
0.8.1
0.8.0
0.7.2
0.7.1
0.7.0
0.6.3
0.6.2
0.6.1
0.6.0

and only it allows me to use "0.12.2" as the latest version available for use.

Thanks for your answer, and I hope you can help me.

Excuse my English ... my English is very basic.

**Comment by jyapayne** [comment]
Hey, sorry, I didn't tell you where the file is located. On Windows, the nw-versions.txt file is located here: "C:\Users\(Your User Name)\AppData\Local\Web2Executable\Web2Executable\files\nw-versions.txt". The one you edited is the one that gets copied for installation. Placing 0.13.0-alpha6 at the top of that file should solve your issue :)

**Comment by soycamiloypunto** [comment]
and Linux? the file is located?

**Comment by soycamiloypunto** [comment]
i used Ubuntu

**Comment by jyapayne** [comment]
Ah, I assumed you were using Windows :P On Ubuntu, the file is located at: "~/.local/share/Web2Executable/files/nw-versions.txt"

**Comment by soycamiloypunto** [comment]
Thank you....

the problem was in the file that was changing .... I was changing the file located in the folder where the program is.

**Comment by jyapayne** [comment]
Glad it worked for you! :) The reason the alphas don't get included is that they are usually pretty unstable, and there's no reliable way to get them programmatically. Let me know if you have more issues :)
