### ISSUE TITLE
Running the app.exe uncompresses on every run

### ISSUE THREAD

**Issue by cmawhorter** [jyapayne/Web2Executable#106]
Not sure if this is by design, but on each application run the entire project is uncompressed to temp and then removed on exit.  0.3.3b.

Steps:

1. Used Web2Executable gui 0.3.3b windows
2. Built project for 32 and 64 which results in a 190mb app.exe
3. Launching app.exe takes many seconds 
4. Launches at .../AppData/Local/Temp/nw264_13422/
5. Exiting takes many seconds and removes that directory

How do I prevent that?  Shouldn't it only uncompress once?

**Comment by jyapayne** [comment]
Unfortunately, that's how NW.js works with packed exes. The only way to have uncompressed data is when exporting to Mac.

Of course, if I added an [Electron](https://github.com/atom/electron) backend, you could have uncompressed folders easily on all platforms.

**Comment by cmawhorter** [comment]
Yup.  I remembered that after posting...   Thanks.
