### ISSUE TITLE
Compression failure [win10x64, w2exe 0.3.2b]

### ISSUE THREAD

**Issue by iLeonidze** [jyapayne/Web2Executable#107]
![image](https://cloud.githubusercontent.com/assets/3584432/11503250/b007e74a-9850-11e5-960c-02aa56bb9f99.png)

Web2Executable v0.3.2b
Windows 10 x64
Can't export my app with the compression (Any of them - from 1 to 9). Export without compression works perfect.

**Comment by jyapayne** [comment]
Yep, you are correct. It must have happened in my latest changes. I'll look into it and fix it up :)

**Comment by jyapayne** [comment]
Hmmm, this seems to be an issue if you are on Windows 10. The permissions are slightly different on Windows 10, even if you are a privileged user it seems. A workaround is to simply run Web2Exe as administrator.

**Comment by Megido6** [comment]
win7 same error. who is Joey?

**Comment by jyapayne** [comment]
@Megido6, That would be me :) Your error is actually a different error that occurs when your node modules have gone too deep. Windows has a path limit of 255 characters and it looks like you hit the limit. You'll have to run some node module flattening program in order to fix it.

**Comment by BloodySucker** [comment]
@jyapayne, add \\?\ to path, this expands the maximum path length to 32767 characters.

As an example:
\\?\C:\Users\Frank\js.js

**Comment by jyapayne** [comment]
That's a very good tip, thank you :) I will attempt to put this in the next release depending on how it goes!

**Comment by jyapayne** [comment]
I believe this is fixed now. Reopen if the issue persists.
