### ISSUE TITLE
Folders and files on output deleted when export

### ISSUE THREAD

**Issue by Inateno** [jyapayne/Web2Executable#108]
Hi, it's me again ^-^

I have a little problem, now when you export the project it's automaticaly cleaning all the output folder.

Example:
output contain /MyProject with:
- windows-x32
- windows-x64
- myCustomFolder

Now if I only export x32, it cleaning all the folder and I have to copy again "myCustomFolder" inside.

Maybe this was excepted ?

++ :)

**Comment by jyapayne** [comment]
Yeah, that's the expected behavior. I wasn't expecting anyone to put a custom folder in the output folder :)

**Comment by jyapayne** [comment]
Why do you need your custom folder there?

**Comment by Inateno** [comment]
First case: I want to export a windows-x32 version different from the windows-x64 (for testing) so I cleaning the folder remove my win64 version

Second case: I want to keep a windows-x32-save / -old version to compare two versions

Third case: I have a custom folder inside the "MyProjectName" folder (inside output) to directly zip it and deliver it (with all win32/64 inside + custom folder).

It's simply to avoid export -> ctrl+x -> ctrl+c at the right place, but if this behavior is better for everyone I'll change my process and export somewhere else and move it manually each iteration/test

In fact it's for process optimization, like the bash call at the end, otherwhise I always forget little thing.

Actually I have a grunt file that compile my JS app, export it, call nw.exe, export project, call bash file that hide some files (and I'm trying to add more automatisation, but I can create a xcopy bash after export in a temp folder and move it at the good place).

I was not sure if this was a bug ;)
