### ISSUE TITLE
LGPL licensing of FFmpeg - is packaging as one exe even allowed?

### ISSUE THREAD

**Issue by JonasT** [jyapayne/Web2Executable#111]
I am just bringing this up in case this hasn't been thought of yet:

If this project spits out a single exe containing nwjs-win with the whole webkit stuff (the description makes it sound like it does), has anyone considered the problems caused by including the LGPL-licensed FFmpeg / ffmpegsumo.dll into the exe?

The LGPL would either require the ffmpegsumo.dll to be very easily exchangable by the end user with a desired alternative compiled .dll (which is hard to fulfill unless the dll is shipped openly separated from the exe instead of contained in it, or unless you provide a detailed guide along with each such exe blob on how to do replace the contained ffmpegsumo.dll) or that the entire resulting thing is released under GPL (which many users of Web2Exe might not want to do)..

Edit: obviously, this is more a problem of the user of Web2Exe rather than the project itself. Still, it would be good if this could be properly addressed if this filed issue applies in any way

**Comment by jyapayne** [comment]
@JonasT, The ffmpegsumo.dll is not included in the exe. It comes included in the same directory as the exported application and can be included/excluded by choice. 

But your point is very correct IF you decide to use the patented technologies of ffmpegsumo (mp3, etc). As far as I know, Roger has compiled only the open source technologies into the standard version of NW.js, which is what I use to pack the exes. See here: https://github.com/nwjs/nw.js/wiki/Using-MP3-&-MP4-(H.264)-using-the--video--&--audio--tags.

This means that unless you explicitly decide to include the LGPL licensed functionality, your exported exe should be under this license: https://github.com/nwjs/nw.js/blob/nw13/LICENSE

**Comment by JonasT** [comment]
Ah, sorry for the unnecessary remark then!

About your FAQ suggestion: why would the app need to be open-source if LGPL-licensed functionality of FFmpeg is used? (Are you referring to the special case when the optional GPL parts of FFmpeg are enabled?)

Also, patents are an entirely different matter and not directly relevant on whether one makes the app open-source or not. It's more like whether you will be a poor person because Thompson demands royalties, lol

**Comment by jyapayne** [comment]
No worries :) 

The app wouldn't need to be open source, that's a bad choice of wording. It would just need to be released under the same license (you couldn't charge money for it without paying royalties)

And yep, you're right about the patent thing :)

**Comment by JonasT** [comment]
The MIT or BSD licenses and also the GPL have wildly different implications, *none* of them is that you cannot sell the program. Therefore you really shouldn't word it that way, because sale of the program is always possible (even if you enabled the GPL FFmpeg extensions - you would just need to provide the source to all customers).

On the other hand, patents aren't even free to use when you don't charge for your program. In practice, nobody might care - but there are no guarantees.

**Comment by jyapayne** [comment]
Ah, that's very interesting information. I wasn't aware that you could still sell the program under the LGPL and GPL licenses. 

Thank you very much for the clarification of these details! :) It seems like you know much more about the licensing concerns than I do. I honestly haven't put much concern (other than keeping the exported exe as open as possible) into the licensing since NW.js's license is what the exe's are released under. Looks like I have some reading to do in terms of what the different licenses actually require the users to do. I assumed I knew, but your comments have convinced me otherwise.
