### ISSUE TITLE
Error When Trying to Export [win10x64, w2exe 0.3.2b] 

### ISSUE THREAD

**Issue by schembora** [jyapayne/Web2Executable#112]
![capture](https://cloud.githubusercontent.com/assets/7702868/12158150/45c7779e-b4a5-11e5-83a1-cfe29597f78d.PNG)
I've tried changing output folders, etc. Nothing seems to be working.

**Comment by jyapayne** [comment]
Why did you close the issue? Did you solve it? I'd like to know so that others can benefit if they have the same issue :)

**Comment by schembora** [comment]
Seemed as though the .git folder was messing something up.
