### ISSUE TITLE
Download of nwjs fails

### ISSUE THREAD

**Issue by btnpushnmunky** [jyapayne/Web2Executable#113]
Just downloaded the app tonight and I'm looking forward to using it.

Check out this error though. Looks like there's something wrong with the path for the download?

![untitled](https://cloud.githubusercontent.com/assets/4810344/12219809/eb31008c-b717-11e5-80c0-14a1998bb35d.png)

**Comment by jyapayne** [comment]
Looks like a bug with the new version. If you use the previous version until I get a fix out, you should be good :)

**Comment by jyapayne** [comment]
Hmm, I'm curious. This works for me on Windows 7, and it looks like you are running Windows 10. Would you mind running Web2Exe as Administrator to see if it fixes the issue? Alternatively, you might be able to work around the issue by changing the download location under "Download Settings". I suspect that it's a permissions issue, but I'd just like to confirm.

**Comment by 2braincells2go** [comment]
If it matters, I run Win 10 and did not have an issue. Worked great.

**Comment by Blatman** [comment]
Maybe I am being a bit picky but all the refs to the path workround from Microsoft use backslashes (\\?\) but the recent update used forward slashes (//?/).  Would this be a possible issue with Win 10's use of win32 api?

Cheers.

**Comment by btnpushnmunky** [comment]
@jyapayne I did try running as Administrator. That didn't work. Changing the download location in Download Settings worked. I seem to have another issue of some sort, but I don't think it's related. Thanks!

**Comment by jyapayne** [comment]
@Blatman, as far as I know, the windows api treats backslashes and forward slashes relatively the same. I just use forward slashes in the code because Python does some funky stuff in windows with back slashes.

@btnpushnmunky Hmmm, maybe I need to make sure the directory is created first. I thought I was doing that, but maybe I'm mistaken. Thanks for testing!

**Comment by btnpushnmunky** [comment]
@jyapayne I thought using os.path solved most slash issues?

**Comment by jyapayne** [comment]
That is true. However, even when joining paths I found that a backslash followed by an "f" causes an unrecognized character.

**Comment by btnpushnmunky** [comment]
OH. A formfeed.

**Comment by Blatman** [comment]
Just tried it myself on Win 10 in Parallels 11 VM on Mavericks using 0.3.4b and downloading 0.12.3 win 64 - worked OK if I used a folder off the C: drive but no good (got the same error as above in screenshot) if I used the W2E default download folder.
W2E 0.3.3b worked fine with the default download folder.

Cheers.

**Comment by jyapayne** [comment]
@Blatman interesting. Thank you for doing that test. I'm in the process of installing a Windows 10 VM now in order to debug the issue.

**Comment by Blatman** [comment]
Just tried 0.3.4.2b on same test as above and worked fine on default folder.

**Comment by jyapayne** [comment]
Awesome, thank you for your assistance :)
