### ISSUE TITLE
Online Update

### ISSUE THREAD

**Issue by weiyukun** [jyapayne/Web2Executable#114]
Firstly,thank you for your app very much~Now,I have a problem.I have made a app by nw.js.Then I want it to have a function that can update when it has a new version.I hope it can download by itself and install by itself.How can i do,please help me,thanks:)

**Comment by jyapayne** [comment]
There is a useful Node package [here](https://github.com/edjafarov/node-webkit-updater) that does what you want with a little elbow grease :)

**Comment by jyapayne** [comment]
Did that package help you? If so, please close the issue :)

**Comment by weiyukun** [comment]
Yes,thank you very much
