### ISSUE TITLE
unable to run the software. Throws error:  File "main.py", line 10, in <module> import validators ImportError: No module named validators

### ISSUE THREAD

**Issue by kamaldeepoodles** [jyapayne/Web2Executable#116]
Hi, I clone the repository on my local machine and tried to run the project from its main directory by writing in console $ python main.py

But got this error

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import validators
ImportError: No module named validators
```

Please help to resolve this error.

**Comment by jyapayne** [comment]
Looks like I have a missing dependency in my requirements.txt. Try running "pip install validators" in a cmd window.

**Comment by jyapayne** [comment]
In the requirements.txt, there is a line ("qt") that is not a requirement. If you remove that line and run ```pip install -r requirements.txt```, the dependencies should install correctly.
