### ISSUE TITLE
v0.4.0b Win 10 Path Too Long

### ISSUE THREAD

**Issue by 2braincells2go** [jyapayne/Web2Executable#119]
Hi Joey.

I have not have been having the issues most of user seem to be having with saving/write errors . v0.3.4.4b, v0.3.4.3b and even v0.3.4.2b (best for me) have worked fine.

Just tried v0.4.0b and very first project resulted in path too long error. No biggie as can work around it. Just thought you may like to know:

![v0 4 0b-win10-2016-02-06_102517](https://cloud.githubusercontent.com/assets/2567500/12867783/a23d3822-ccbc-11e5-9397-d5962288e99d.png)

**Comment by 2braincells2go** [comment]
Spoke too soon... Now I cannot get any versions to work. Getting messages about directory does not exist in "users". Out of time for the day so will try to dig deeper tomorrow.

Few days ago Win 10 updated and seemed like big update so who knows, maybe that is issue.

**Comment by jyapayne** [comment]
Hey Woody! Thanks for letting me know about this. It's weird that you're still getting the "path too long" error, since the "//?/" is prefixed in the error message. I'll have to take a look at that. 

As for the image error, I believe I fixed it, but if you could test the latest [prerelease](https://github.com/jyapayne/Web2Executable/releases/tag/v0.4.1b) when you get the chance, that would be awesome :)

**Comment by jyapayne** [comment]
Also, could you capture the error for the directory not existing?

**Comment by 2braincells2go** [comment]
Hello Joey. Will try the prerelease shortly and report back

I keep forgetting about the logs in Web2Exe files folder. Here is little taken from it about directory error:

`"[Errno 2] No such file or directory: '//?/C:\\\\Users\\\\ccnet\\\\AppData\\\\Local\\\\Temp/webexectemp/php-webkit.nwf\\\\node_modules\\\\gulp\\\\node_modules\\\\gulp-util\\\\node_modules\\\\dateformat\\\\node_modules\\\\meow\\\\node_modules\\\\read-pkg-up\\\\node_modules\\\\read-pkg\\\\node_modules\\\\path-type\\\\node_modules\\\\graceful-fs\\\\legacy-streams.js'"), ('//?/C:\\php-webkit\\node_modules\\gulp\\node_modules\\gulp-util\\node_modules\\dateformat\\node_modules\\meow\\node_modules\\read-pkg-up\\node_modules\\read-pkg\\node_modules\\path-type\\node_modules\\pinkie-promise\\node_modules', '//?/C:\\Users\\ccnet\\AppData\\Local\\Temp/webexectemp/php-webkit.nwf\\node_modules\\gulp\\node_modules\\gulp-util\\node_modules\\dateformat\\node_modules\\meow\\node_modules\\read-pkg-up\\node_modules\\read-pkg\\node_modules\\path-type\\node_modules\\pinkie-promise\\node_modules', "[WinError 206] The filename or extension is too long: '//?/C:\\\\Users\\\\ccnet\\\\AppData\\\\Local\\\\Temp/webexectemp/php-webkit.nwf\\\\node_modules\\\\gulp\\\\node_modules\\\\gulp-util\\\\node_modules\\\\dateformat\\\\node_modules\\\\meow\\\\node_modules\\\\read-pkg-up\\\\node_modules\\\\read-pkg\\\\node_modules\\\\path-type\\\\node_modules\\\\pinkie-promise\\\\node_modules'"), ('//?/C:\\php-webkit\\node_modules\\gulp\\node_modules\\gulp-util\\node_modules\\dateformat\\node_modules\\meow\\node_modules\\redent\\node_modules\\indent-string\\node_modules\\repeating\\node_modules\\is-finite\\node_modules', '//?/C:\\Users\\ccnet\\AppData\\Local\\Temp/webexectemp/php-webkit.nwf\\node_modules\\gulp\\node_modules\\gulp-util\\node_modules\\dateformat\\node_modules\\meow\\node_modules\\redent\\node_modules\\indent-string\\node_modules\\repeating\\node_modules\\is-finite\\node_modules', "[WinError 206]`

**Comment by 2braincells2go** [comment]
Ok sir, I tried v0.4.1b and still having issues.

First I tried was using php-webkit and second was older project that worked fine in few Web2Exe releases ago. I am attaching to error log files (zipped).

The one named "error - Copy.log" was first run attempt (v0.4.1b) at using php-webkit from my c:\php-webkit directory. Placed it there to test path too long error.

The second one named "error.log" is second attempt at using past project - which worked fine, but now does not. It creates the mac version but NOT the windows exe in output directory.

Hope I am making myself clear, still early and only on second cup of coffee:)

Let me know if there is anything can test, be more than happy to help in any way Joey.


[files.zip](https://github.com/jyapayne/Web2Executable/files/120770/files.zip)

**Comment by jyapayne** [comment]
Hey Woody,

Part of the reason you're getting these errors is because you might be installing all of the dependencies of php-webkit, instead of only the required ones.

Delete the `node_modules` directory and open up a cmd window in the `php-webkit` directory and then execute:

```
npm install --production
```

which will not install the long list of dependencies required for development. Also, when you're copying the php-cgi.exe into the `bin/php` directory, make sure you copy the `phpX.dll` as well, where `X` is the major version number. So if you are using PHP 5.4, you'd copy over php-cgi.exe and php5.dll.

Of course, this is just a workaround for long paths. I'm updating the code to take care of long paths using php-webkit as a test project. Hope this helps!

**Comment by jyapayne** [comment]
You'll probably want to only use PHP 5.X (Non-thread safe). I couldn't get PHP 7.X to work.

**Comment by 2braincells2go** [comment]
Thanks Joey! You should have been a teacher, your patience is outstanding:)

I used an old working version of php-webkit when first testing with v0.4.0b, not sure how I ended up the the node_modules directory, baffles me. All I did was open project in v0.4.0b. But, dealing with terrible cold (flu) so perhpas the cold meds have my head in clouds...

I know have it at least creating the exe files by deleting the node_modules directory. But when exe opens, get the red screen with "Error: Cannot find module 'express'" Think it best for me to delete everything and start fresh using v0.4.1b

On another note, now getting the error below on most all exported projects, which has never happened. Really starting to wonder if last Win 10 update changed something:

![2016-02-07_115139](https://cloud.githubusercontent.com/assets/2567500/12874415/328ba5bc-cd99-11e5-83b3-42228655c9f2.png)

**Comment by jyapayne** [comment]
Yeah, it looks like some permissions changed on that folder. What happens if you manually delete `webcamcodescanner\output` and rerun?

**Comment by jyapayne** [comment]
I've also updated the prerelease to try and eliminate the path errors :)

**Comment by 2braincells2go** [comment]
Thanks man! I deleted the output folder and that solved the "failed to remove" issue.

Tried the new prerelease and things seem to be fine. Had meant to bring up slider not displaying number steps, but totally forgot.

Cannot get php-webkit to display my php files (or phpinfo) in Web2Exe text output, but seems that has something to do with my php.ini setup. Will have to explore what is happening there.

Thanks you so much for your help Joey.

**Comment by jyapayne** [comment]
No problem! (And thanks for saying I should have been a teacher before :))

I've got a zip file that I've attached of php-webkit that works for me. Try to unzip it and export it with Web2Exe to see if it works. Hope your flu is a bit better!

[php-webkit.zip](https://github.com/jyapayne/Web2Executable/files/121625/php-webkit.zip)

**Comment by 2braincells2go** [comment]
You version worked. Now got me thinking the version of PHP I chose (5.5.32 Non-thread safe).

Only issue I had was the folder permission and have to delete output folder every time remake.

But it working and all I can ask.

Cheers buddy!
