### ISSUE TITLE
Low performance on windows compiled. I/O problem at startup

### ISSUE THREAD

**Issue by r1si** [jyapayne/Web2Executable#120]
Hi, 
first of all thanks you for your software, it's work like a charms.... :+1: 
But, I have a performance problem with windows compiled version (x32 or x64 is the same), 
when I try to run the windows one, my I\O and the CPU go high, and the startup it's very slow..

For example, the same application on: 
OSX : 10 seconds
LINUX : 13 seconds
WINDOWS 45 secondos :o: 

any idea? 

thanks you very much ! 

Elia

**Comment by jyapayne** [comment]
It's most likely due to unpacking the binary at the start, which may be less efficient on Windows. You could always try [Electrify](https://github.com/jyapayne/Web2Executable) to see if the start times are any different, since it doesn't have any unpacking requirements.

**Comment by jyapayne** [comment]
In the latest release, using NW.js 0.13.0 rc3 to export, I've put in an experimental feature that should alleviate startup problems on Windows. If you check the "Uncompressed" option in compression settings, your files should be uncompressed when you export.

**Comment by r1si** [comment]
Thanks a lot. 
But I switch to Electrify as you tell me :+1:
