### ISSUE TITLE
nw.js 0.13 compatibility

### ISSUE THREAD

**Issue by le717** [jyapayne/Web2Executable#121]
Quick question for ya, since I can't seem to find any info on the matter.

Does this support building with nw.js 0.13 or will support for that be added once it comes out of beta? I am looking to upgrade a node app I am working on to 0.13 but need to be sure I can still build executables.

Thanks! :)

**Comment by jyapayne** [comment]
Hey!

As it stands, there isn't support for nw.js 0.13.0 in Web2Exe. I was waiting for 0.13.X to come out of beta, but feel free to file a feature request issue for nw.js 0.13.X support and I might be able to integrate it earlier :)

**Comment by le717** [comment]
Thank you for your quick response. Hopefully I filed the request correct and I look forward to 0.13 support. You have a great program here. :)
