### ISSUE TITLE
Feature request: nw.js 0.13.X support 

### ISSUE THREAD

**Issue by le717** [jyapayne/Web2Executable#122]
Please support building executables with nw.js 0.13. :)

**Comment by ax88** [comment]
+1

**Comment by jyapayne** [comment]
I've been busy lately, so I haven't had a chance to work on this very much. Just know that it will be out soonish (a week or two max). The base work is done, I just need to rework the version retrieval a bit to get the latest RC versions.

**Comment by jyapayne** [comment]
So I did some quick work this morning and tried to get a version out that works. Let me know if the [latest release](https://github.com/jyapayne/Web2Executable/releases/tag/v0.4.3b) works for you guys!

**Comment by jyapayne** [comment]
This feature should be done with 0.4.3b. If there are any issues with it, feel free to open another issue!

**Comment by le717** [comment]
I'm sorry I didn't get to test it. My laptop broke right before you made the changes and I have yet to get it back. :( However, thank you for your quick work! I am very thankful for it. :)

**Comment by jyapayne** [comment]
Alright, no worries :) Hope you get it fixed!

**Comment by ax88** [comment]
0.13 RC3 is working for me, thanks :)
