### ISSUE TITLE
Missing python library

### ISSUE THREAD

**Issue by Forecaster** [jyapayne/Web2Executable#127]
When I try to run web2exe-linux on my linux machine
`./web2exe-linux`
it produces this error:

> Error loading Python lib '/tmp/_MEIKj2OVQ/libpython3.4m.so.1.0': /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /tmp/_MEIKj2OVQ/libpython3.4m.so.1.0)

I don't have any experience with python, so I'm at a loss what to do here.

**Comment by jyapayne** [comment]
What version of linux are you running on? And on 32-bit or 64-bit?

**Comment by Forecaster** [comment]
It is Ubuntu 12.04.5 Server x64

**Comment by jyapayne** [comment]
Ah, it looks like because I built Web2Exe with Ubuntu 14.04, it linked glibc 2.17. That means that you can't use it with 12.04 because the highest version of glibc for 12.04 is 2.15. Is there a reason that you are still on 12.04 and not 14.04?

**Comment by Forecaster** [comment]
Fear of updating because of the break risk. It's a production server and I don't have a backup machine. If it goes down my sites go down with it.

**Comment by jyapayne** [comment]
Ah, that's too bad. I can try building a release for 12.04 when I get the chance and see if it fixes your issue.

**Comment by Forecaster** [comment]
You don't have to do that if it's inconvenient. I plan on creating a new install on a new hard drive using a virtual machine so I can move things over while still keeping the server up. I just need to find time to do it.
