### ISSUE TITLE
node-remote setting is replaced with node_remote

### ISSUE THREAD

**Issue by eemi2010** [jyapayne/Web2Executable#129]
node-remote settings is getting changed to node_remote. Wich is not supported in version >= 0.13.
This is happening in the latest GUI for Mac.

Any way I can fix this locally ?

**Comment by jyapayne** [comment]
Ah, yes. I left that in because of backwards compatibility. It shouldn't matter if the field is blank in the GUI and you export. Which version of NW.js are you exporting with and what's the error you experience?

**Comment by eemi2010** [comment]
I m targetting nw.js 0.13.4 the thing is if i put node-remote in my package.json and left the field empty in the gui the entry is removed from tje pachage.json after the export and dont get applied.
Someway I get prevent the gui from overriding the package.json ?

**Comment by eemi2010** [comment]
Actually the node-remote entry is removed during the build.

**Comment by jyapayne** [comment]
I'm still a bit confused on what your issue is. What is the error that you get after you export the application?

**Comment by eemi2010** [comment]
node-remote is not working . it gets delete from the package.json while building

**Comment by jyapayne** [comment]
Ah, okay, I understand now. It looks like Web2Exe is renaming your field to node_remote and removing the required node-remote field. I misunderstood the documentation for NW.js regarding the node-remote change and thought that they renamed it to "node_remote". I will update the code to fix this and put up a new build. Sorry for the confusion.

**Comment by eemi2010** [comment]
No worries. Keep up the good work. You rock :)
