### ISSUE TITLE
Mac 32-bit option still enabled on NW.js >= 0.13.X

### ISSUE THREAD

**Issue by Montoya** [jyapayne/Web2Executable#130]
I've just installed the latest version of Web2Exe and every time I try to export I get this message as soon as the app tries to download the ZIP for any platform. 

![screen shot 2016-04-18 at 10 56 03 am](https://cloud.githubusercontent.com/assets/19909/14608554/37219530-0554-11e6-8489-2eb0378a4eeb.png)

**Comment by jyapayne** [comment]
This is because you're trying to export to Mac OSX 32 bit, which doesn't exist for NW.js > 0.12.X. Switch to 64 bit and it should be good.
