### ISSUE TITLE
Unable to open Linux export on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by jonmulcahy** [jyapayne/Web2Executable#131]
I am trying to generate a linux version of my HTML5 app. I'm generating the apps from an OS X 10.11 laptop, and the Windows and OS X versions work perfectly. When I copy the linux-x32 and linux-x64 folders to my Ubuntu virtual and run the .desktop file, it gives me an error "There was an error launching the application".

Any thoughts or logs I can look for?

**Comment by jyapayne** [comment]
Did you make sure to change the paths within the desktop file? The paths have to be absolute, so they are probably set to your export folder on OSX.

**Comment by jonmulcahy** [comment]
@jyapayne I did not! They were set to my export folder. So if I was to distribute this, I wouldn't know where people would put it, so would I have to provide some sort of script to update that location?

**Comment by jyapayne** [comment]
That's one way to do it. Another way is to provide an install script that installs your app into the same location every time (or a custom location based on user input). Then you could take the default path or the path they entered and replace the paths in the .desktop file with the new one. Whatever works for you :)

**Comment by jonmulcahy** [comment]
cool, I'm trying to get a game on steam, and I'd love to support linux as well, but I just don't have much experience with it.

you can close this.
