### ISSUE TITLE
Python 2 getheaders is used instead of Python 3 get_all

### ISSUE THREAD

**Issue by digital-flowers** [jyapayne/Web2Executable#132]
hi currently i decided to move from nw-builder to this project because there is too much missing features in nw-builder i am using mac os cli version of your project the execution giving me Done with no issues but there is no output anywhere ! here is my command:

`./web2exe-mac "../builds-cache" --main "../builds-cache/app/app.html" --nw-version 0.14.0 --output-dir "../builds" --export-to mac-x64`

**Comment by jyapayne** [comment]
Looks like some error probably happened. The default behavior is to not show much output. If you add the flag "--verbose" what is the output?

**Comment by digital-flowers** [comment]
i got this error "AttributeError: 'HTTPMessage' object has no attribute 'getheaders'"

**Comment by jonmulcahy** [comment]
does the GUI version work at all?

**Comment by jyapayne** [comment]
@digital-flowers I've found the issue and it seems it's some Python 2 code that hadn't been swapped yet. Most people use the GUI version, so sometimes the cmd version gets neglected a bit :)

@jonmulcahy Yep!

**Comment by jyapayne** [comment]
@digital-flowers Please try the latest CMD download from the releases page to see if it works for you now.

**Comment by digital-flowers** [comment]
thank you, but sorry i had no time so is write my own script to build nwjs anyway maybe i will try it in my next project i like the idea it is really great tool keep it up :)

**Comment by digital-flowers** [comment]
another thing i also have noticed that you need to update all download links inside settings.cfg, the files names now in the form of http://dl.nwjs.io/v{version}/nwjs-v{version}-{platform}-{arch}.zip i noticed the links inside your tool still pointing to old links witch is deprecated and maybe removed soon

**Comment by jyapayne** [comment]
@digital-flowers No worries. And thank you for the information. My tool actually transforms to those links inside the Python code if the version is >= 0.13.0.
