### ISSUE TITLE
CMD-Q does not quit the app

### ISSUE THREAD

**Issue by jonmulcahy** [jyapayne/Web2Executable#133]
I've searched around and it seems like many projects based on NW.JS will not quit using CMD-Q on the mac. I've tried a few workarounds I've found, but nothing seems to work. What are others doing?

**Comment by jyapayne** [comment]
Which version of NW.js are you using? I just tested using 0.14.1 and it seems to close the application fine when hitting CMD-Q.

**Comment by jonmulcahy** [comment]
I tried 13.0 beta7, and 14.1 and it didn't work in either. I am wrapping a game, maybe something in the game engine is blocking the command. I'll do some investigating, you can close this

**Comment by jyapayne** [comment]
Alright, hope you figure it out!
