### ISSUE TITLE
Can't find icon file after making.

### ISSUE THREAD

**Issue by rkarroll** [jyapayne/Web2Executable#134]
Hey there.  This seems like a really awesome tool although, I do seem to be having one issue.  When running the created .exe I get the below error.  Any ideas on how I can fix this?  

Thanks!

![image](https://cloud.githubusercontent.com/assets/5384248/14876976/3de6d78c-0ce7-11e6-8114-65cc207875bc.png)

**Comment by jyapayne** [comment]
What options are you exporting with?

**Comment by rkarroll** [comment]
Thanks for responding so fast!  Here are the options.   I appreciate any assistance you can provide.

When I looked at package.json it seems that // were added for each directory listed i.e. "mac_icon": "assets//images//icon_800.png"  Thanks again!

![image](https://cloud.githubusercontent.com/assets/5384248/14905885/6d69d526-0d83-11e6-8229-15278e060f8b.png)

![image](https://cloud.githubusercontent.com/assets/5384248/14905893/85ada900-0d83-11e6-9479-629a9bdc2230.png)

![image](https://cloud.githubusercontent.com/assets/5384248/14905902/9b35c88e-0d83-11e6-9fed-7a9c80c33925.png)

![image](https://cloud.githubusercontent.com/assets/5384248/14905908/ad26e852-0d83-11e6-9d27-6812d57e8988.png)

![image](https://cloud.githubusercontent.com/assets/5384248/14905913/c2bc0ab2-0d83-11e6-82f5-f4adf1c8fc46.png)

**Comment by jyapayne** [comment]
Hmm your options look good. I just tried exporting using your options and they work fine. What bothers me is the "Failed to load extension" message. Can you post your package.json contents?

**Comment by rkarroll** [comment]
Hey Joey, it was something I did on my end.  Sorry to take your time with this!  

Great tool!
