### ISSUE TITLE
CMD version ends up silently, when using --package-json

### ISSUE THREAD

**Issue by saitonakamura** [jyapayne/Web2Executable#136]
I'm trying to create a script to build my application from command line

`".\Web2ExeWin-CMD\web2exe-win.exe" ".\app" --main index.html --export-to windows-x32 windows-x64 --package-json ".\app\package.json"`

When I run it it says
`Updating nw versions...
Done.
`

And than, silently ends up leaving me with a console window and feeling of little dissatisfaction
When I remove `--package-json` option it gives my `No such file or directory: '.\\app\\package.json'`, and then I understand that I should change `".\app"` to `"..\app"`

But I think it should give me a readable mistake

**Comment by jyapayne** [comment]
Interesting. Can you add the `--verbose` flag and see if any errors come up?

**Comment by saitonakamura** [comment]
I'm ashamed, but it seems I can't reproduce it
Premature alarm

**Comment by jyapayne** [comment]
Okay, I'll close the issue.
