### ISSUE TITLE
CMD version not taking data from --package-json option but writes data to it

### ISSUE THREAD

**Issue by saitonakamura** [jyapayne/Web2Executable#137]
I have a script
`".\Web2ExeWin-CMD\web2exe-win.exe" "..\app" --main index.html --export-to windows-x32 --package-json "..\app\package.json"`
And it seems that it's ignoring my `package.json` cause it tries to download binaries (which is already downloaded, but in the different directory, which is presented in `package.json`), using default app names and stuff
But what's more suprising, that it writes data in my `package.json` so it ends up with default values
I was thinking that `--package-json` option meant to read the data from `package.json` and use it to pack the application, not vice versa
And what option should I use to achieve my goal?

I'm using v0.4.7b

**Comment by jyapayne** [comment]
That may be a left over issue from a while back. I've had this issue before and thought that I fixed it, but it looks like you're right. Thank you for letting me know about it! I'll try to fix it this weekend :)

**Comment by jyapayne** [comment]
I can't seem to reproduce the issue you're experiencing. When I load the package.json from another location, all Web2Exe does is load the specified package.json and does not write to it. 

Would you be able to make a small project with a package.json that showcases this issue?

**Comment by jyapayne** [comment]
Oops, nevermind. I can reproduce it now :) Disregard that last comment.
