### ISSUE TITLE
no output executables

### ISSUE THREAD

**Issue by yell-oh** [jyapayne/Web2Executable#138]
Hi, really like that project, but I have a Problem with getting executables in the output folder.

I've downloaded the Web2Exe v0.4.8b for mac (Gui) / also tried with the Web2Exe v0.4.7

If I build my project there is an output folder and a folder inside that with my app name. But no executables. I have a second project, which was just a try with threejs and stuff - that gets build... I really dont know whats the difference between those projects, they seem very much the same (formal)...

Is there a log or something that tells my why no executable is build?

Thanks....

**Comment by jyapayne** [comment]
Hi, thank you for using it and helping make it better :)

There is a log located at `/Users/<username>/Library/Application Support/Web2Executable/files/error.log`
That should display at least an error and then maybe we can see what is wrong.

**Comment by yell-oh** [comment]
Hi, 

thanks for that fast answer.

I found that log and here is indeed an error:

ERROR      2016-05-18 16:08:49,611 command_line.py: 94 my_excepthook - Traceback (most recent call last):
  File "main.py", line 130, in run
  File "command_line.py", line 883, in make_output_dirs
  File "command_line.py", line 920, in get_app_nw_loc
  File "utils.py", line 127, in zip_files
  File "zipfile.py", line 1326, in write
FileNotFoundError: [Errno 2] No such file or directory: 'node_modules/.bin/wscat'


What is wscat? ;) Did you ever heard that?

**Comment by jyapayne** [comment]
It looks like when you removed an npm module, you didn't use `npm uninstall wscat`, which makes it so that there is a symbolic link that leads to nothing. If you delete that file, and maybe others like it if the error keeps happening, the program should work.

**Comment by jyapayne** [comment]
This should be fixed with the latest release. I set Web2Exe to ignore these broken files.
