### ISSUE TITLE
windows-x64 and node-webkit >0.14.6

### ISSUE THREAD

**Issue by wehowski** [jyapayne/Web2Executable#142]
Hello,
first of all thanks for the work.

Everything works fine, but when I compile with node-webkit version greater than 0.14.6 then the application terminates immediatly after clicking the .exe.
The .exe for win 32 bit is working but not 64.
The process or programm is terminated without showing the window (so I could not debug easy)

Other systems I did not test.

Thanks for help.

**Comment by jyapayne** [comment]
You're very welcome :) I will take a look at this issue as soon as I get the chance. Thanks for reporting it!

**Comment by jyapayne** [comment]
Which version did you try exporting with specifically? I just tried 0.15.1 and 0.15.0 on Windows 7 x64 and Windows 10, and the compiled exe works for me. Is your code doing anything architecture specific with native modules or anything?

**Comment by wehowski** [comment]
I tried on Windows 8.1.
> Is your code doing anything architecture specific with native modules or anything? 
I am not sure, I will try to exclude some modules and maybe find the problem in the code...

**Comment by wehowski** [comment]
@jyapayne: 
Can I give you (e-Mail?) you a deeplink to my source code?

**Comment by jyapayne** [comment]
Sure :) I can try to take a look at what's going on. My email is jyapayne at gmail.com

**Comment by wehowski** [comment]
Hello  jyapayne,
thank you, I wrote you an E-Mail.

**Comment by wehowski** [comment]
Thank you for help!
As I believe so far it is an nw.js issue as I can reproduce this with a blank project and download from nwjs?

**Comment by jyapayne** [comment]
Yeah, it's most likely an nw.js issue. Please file an issue with their repo :)
