### ISSUE TITLE
Failed to remove file with 0.4.1b

### ISSUE THREAD

**Issue by Inateno** [jyapayne/Web2Executable#144]
Hi, I have a blocking error (windows issue I think lol)

![image](https://cloud.githubusercontent.com/assets/1068709/16222043/5f3a12bc-3796-11e6-8c49-0eff16bc5dbc.png)

This happen even if the folder exist or not (if the folder doesn't exist, the creation of the folder work, but 
I have an empty folder).

Should I clean the traces of the olders version ?

**Comment by 2braincells2go** [comment]
I feel your pain:)

If you are using Win 10, recommend you use Users\Public\Public Documents folder.

It is very strange. On one Win 10 machine never have issues but on another I must use the public documents folder or have errors like your randomly.

**Comment by Inateno** [comment]
Windows 7 ^^

**Comment by jyapayne** [comment]
@Inateno There is was a bug with clearing previous errors that would cause previous errors to show even if there were none. This means even if a folder doesn't exist, you'd get the error. But the export should have still worked. The workaround is to either download 0.4.11b or close and reopen Web2Exe :)
