### ISSUE TITLE
Anyway to embed SQLite?

### ISSUE THREAD

**Issue by warlachance** [jyapayne/Web2Executable#145]
I've converted a web app using Web2Executable; however, the app obviously still requires a connection to access the database/server. Is there anyway to embed SQLite within the converted app so that the app can operate offline as a truly native, standalone app?

By the way, this program is awesome! Thanks for all you hard work on Web2Executable.

**Comment by williamd1k0** [comment]
I've tried using SQLite with **nwjs** but did not succeed with any node module. 
I was able to use SQLite with nodejs but not in nwjs.
After getting days trying unsuccessfully, I have compiled a small program I wrote in python to run SQLite using sub-process.
I still can not run natively, unfortunately :disappointed:

**Comment by jyapayne** [comment]
@warlachance I haven't personally done this but my first try would be with the sqlite3 module for npm. They have a few notes on how to get it to work with node-webkit, so they might be transferable to nwjs. However, I assume that @williamd1k0 has already attempted this.

**Comment by williamd1k0** [comment]
Yes, I tried, but for some reason does not work in nwjs 0.12. 
I'm using nwjs 0.12 for a few reasons, but that's beside the point.
I don't know if I ended up doing something wrong...
Also, I have not tested the module in nwjs ^0.13.

**Comment by jyapayne** [comment]
I managed to get it working using the following steps:

1. Install [.NET Framework 4.5.2](https://www.microsoft.com/en-us/download/details.aspx?id=42642) (Only on Windows 7. Also, **make sure you are on SP1 of Windows 7**)
2. Install [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) **Make sure to select custom install and select BOTH WIndows 8.1 and Windows 10 SDK**
3. Install Python 2.7 (I used 2.7.3, but it should work with higher versions)
4. Install [LatestNode](https://nodejs.org/en/download/)
5. Install [Git for windows](https://git-scm.com/download/win)
6. Set global MSVC version: 

```
npm config set msvs_version 2015 --global
```

7. Install **latest** nw-gyp 

```
npm install -g git+https://github.com/nwjs/nw-gyp.git
```

8. Navigate into your project directory with cmd.exe and execute this: 
```
npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=ia32 --target=0.15.2 --python=C:\Python27\python.exe
```

(Use target=x64 for 64 bit, you'll have to execute this twice if you want both)

9. If there were no errors, you should be good to run the attached sample project with the following output:

![sqlite](https://cloud.githubusercontent.com/assets/2645657/16342852/68c5e466-39f1-11e6-99cb-9fd10c3408df.png)

[SqliteTestProject.zip](https://github.com/jyapayne/Web2Executable/files/332040/SqliteTest.zip)

**Comment by warlachance** [comment]
The web applications I am working with are basic JavaScript/HTML applications. So what would I use instead of the Python/.NET/C++ commands? Sorry if my questions are dumb. I am a computer science student going into my senior year of undergrad and my experience with web applications is minimal. Thank you for your help!

**Comment by jyapayne** [comment]
@warlachance You might be able to use this: https://github.com/nwjs/nw.js/wiki/Save-persistent-data-in-app

**Comment by warlachance** [comment]
Ah, I see how this might work. I'm going to mess around with this a little bit and see what I can figure out. I'll probably work with it today and come back on Monday and see what I can figure out. @jyapayne I'll keep you posted in this thread. Once again, thank you for your help! I greatly appreciate it.

**Comment by jyapayne** [comment]
You're very welcome :) Looks like you also might be able to use [nedb](https://www.npmjs.com/package/nedb). It's implemented entirely in Javascript, however, this is a NoSQL database that uses a custom query language. Looks pretty cool though :)

**Comment by williamd1k0** [comment]
I never got to use directly NoSQL but this **nedb** looks pretty interesting.
I just will not be able to give attention to it now because I'm focusing on another project (written in python).
Thanks @jyapayne o/

**Comment by warlachance** [comment]
Hey @jyapayne I sent you an email regarding some more specific questions about this issue. Is 	jyapayne@gmail.com a good email to reach you at?

**Comment by jyapayne** [comment]
@warlachance Yes, it's fine to reach me at that email. I will be away starting tomorrow for vacation, so I won't be responding to emails until the 18th.
