### ISSUE TITLE
Minor bug - does not remember Inject JS Start

### ISSUE THREAD

**Issue by wehowski** [jyapayne/Web2Executable#146]
If I fill out the form field for "Inject JS Start", and then close Web2Exe.exe, it is not remembered as the other option settings. So I have to fill out this field everytime I re-open my project.

No real error but easy to fix I guess...!?

...
OT:  The other issue is still open here: https://github.com/nwjs/nw.js/issues/4976
...

**Comment by jyapayne** [comment]
Which version of Web2Exe are you using? That issue should be fixed in the latest version 0.4.11b.

**Comment by wehowski** [comment]
Indeed, an updated solved the issue, thanks!
(I was using the WinSetup.zip wich installed v04.9)
