### ISSUE TITLE
Show Toolbar option not working

### ISSUE THREAD

**Issue by warlachance** [jyapayne/Web2Executable#147]
I'm converting some apps using the Web2Exe tool and I'm checking the "Show Toolbar" option but on my final output the toolbar is not there. I really liked this feature cause it helped me debug. Any idea as to why this isn't working?

**Comment by jyapayne** [comment]
Ah, yes. You'll notice if you hover over that option that it says the option is deprecated. For newer versions of NW.js that you select (greater than 0.13.0), you have to select "SDK Build" in the "Download Settings" tab. Then, you can enable the developer tools as described [here](http://docs.nwjs.io/en/latest/For%20Users/Debugging%20with%20DevTools/) using the keyboard shortcuts.

**Comment by jyapayne** [comment]
The only reason that this option still exists is because some people still like to use NW.js 0.12.X

**Comment by warlachance** [comment]
Got it. Thanks!
