### ISSUE TITLE
can‘t run it on Ubuntu

### ISSUE THREAD

**Issue by felix307253927** [jyapayne/Web2Executable#148]
I can't run it on my Ubuntu with ordinary users, but I can run with the sudo,, my Ubuntu version is 16.04lts.
![image](https://cloud.githubusercontent.com/assets/9459249/16481856/dcc70fdc-3edf-11e6-8265-b282a057af2b.png)

**Comment by jyapayne** [comment]
I've only tested the Linux version on Ubuntu 14.04, so there could be issues on newer versions. I just installed 16.04, so I'll give this issue a look when I have some time.

**Comment by jyapayne** [comment]
I can indeed reproduce the issue. It's probably a library issue. Can you test [this version](http://www.mediafire.com/download/36wsjz8l6r3lq6e/Web2ExeLinux-v0.4.11b.zip) that I built on 16.04?

**Comment by jyapayne** [comment]
I'm going to assume this worked for you. I'm closing this issue and will be uploading the new version.
