### ISSUE TITLE
Change executable description in Windows

### ISSUE THREAD

**Issue by tekrat** [jyapayne/Web2Executable#149]
When I create an application in Windows the file name is fine (something.exe instead of nwjs.exe).  However when I create a shortcut Windows and other application looks at the 'Description' metadata of the file to generate the shortcut's title.  See 'description' in the linked image below:

https://s32.postimg.org/luovu9j9h/2016_06_30_09_17_02_windows_x32.png

Please have Web2Executuble set the description or can a method to manually set that be added to the FAQ page.

**Comment by jyapayne** [comment]
Hmm, this is tricky. I'm not quite sure where that piece of text is stored specifically for the shortcut. I'll try to figure it out when I get the chance. Thanks for filling this issue!

**Comment by jyapayne** [comment]
On second look, it looks like this is an issue with NW.js itself, not my application. Really, NW.js should do this for you based on the manifest file. Please file an issue with the NW.js repo.
