### ISSUE TITLE
Minifying ability request

### ISSUE THREAD

**Issue by EthraZa** [jyapayne/Web2Executable#15]
Would be great if Web2Executable add an option to use Google Closure Compiler or other minifying tool on the JS, CSS, JSON and HTML files before to pack the project.

**Comment by sapioit** [comment]
Thanks! That's a awesome suggestion!

**Comment by saitonakamura** [comment]
I'm not strongly against it, but don't you think it's more the responsibility of gulp or grunt, to make project ready for deployment?

**Comment by jyapayne** [comment]
@saitonakamura You raise a good point. I agree with you that it's the responsibility of an external tool. I've tried to implement this, but it never quite works out right and is very difficult. I think I'll recommend your suggestion if other issues are raised concerning this same topic and close this issue. Thank you for your input :)

**Comment by williamd1k0** [comment]
I suggest using some external command or script. You could create a way to execute this command/script before and after generating the executable. But only on a copy of the project.

I for example do a copy of the entire project to a temporary folder, run a script to do some cleaning, and then I use this folder to generate the executable.

**Comment by jyapayne** [comment]
@williamd1k0 I totally missed this post. That's a good way of doing things, and it makes sense to only do it on a copy of the folder in order not to mangle the project. I'll keep that in mind and maybe implement it later if I have some spare time.
