### ISSUE TITLE
 I can not run on Linux Ubuntu 15.10

### ISSUE THREAD

**Issue by accncc** [jyapayne/Web2Executable#155]
ac@ac-desktop:~/app/Web2ExeLinux$ chmod +x web2exe
ac@ac-desktop:~/app/Web2ExeLinux$ ./web2exe
Error segmentation (made of memory dump)

Please help me!

**Comment by jyapayne** [comment]
Can you try running [this version](http://www.mediafire.com/download/36wsjz8l6r3lq6e/Web2ExeLinux-v0.4.11b.zip)?

**Comment by accncc** [comment]
Thank!
