### ISSUE TITLE
[Feature Request] - GUI - Option to save the configurations and reload the configuration

### ISSUE THREAD

**Issue by yesudas** [jyapayne/Web2Executable#157]
Need an option to save the configurations made from all tabs "App Settings", "Window Settings", "Export Settings", etc to a local file.
Then there should be an option provided in the file menu top load this file.

This helps the user to avoid filling fields again and again.

**Comment by jyapayne** [comment]
You mean to load cross project? Web2Exe already saves the settings to your package.json file to reload.

**Comment by jyapayne** [comment]
Can you elaborate more on what your specific use case is? What do you do manually that this feature could fix for you?

**Comment by jyapayne** [comment]
Closing this because I don't know what you meant and you didn't clarify.
