### ISSUE TITLE
Included Mac binary of PhantomJS not executable when built into Mac app

### ISSUE THREAD

**Issue by EddieK31** [jyapayne/Web2Executable#159]
The application that I am working on required the use of PhantomJS.  The single file executable  of PhantomJS is put in the path of the application (in system specific folders).  When accessing the Windows version it works just fine.  When accessing the Mac version, on a Mac, the file can not be run.  It appears that the file is no longer executable.  I have tried both building on Windows and Mac with the same results.

Any input would be greatly appreciated.

**Comment by jyapayne** [comment]
Would you be able to bundle a little sample project that showcases the behaviour you are seeing?

**Comment by EddieK31** [comment]
What it looks like is it just isn't marking the file +x, executable.  Let me know if this help and if you still need a simple project I will attempt to create one.

Thanks for the quick reply.  Great job, I love it.

Scott
On 8/18/2016 2:37:55 PM, Joey <notifications@github.com> wrote:
Would you be able to bundle a little sample project that showcases the behaviour you are seeing?

**Comment by jyapayne** [comment]
Hmm, you're probably right. I had an issue with this before and thought I solved it. I'll have a look at it when I get the chance. Glad you like it! :)

**Comment by EddieK31** [comment]
Thanks Joey.

**Comment by jyapayne** [comment]
It looks like the copy operation I use [from here](https://docs.python.org/2/library/shutil.html#shutil.copytree) is already supposed to keep file attributes.

A simple project would help a lot so I can see exactly how you are running the application and I can easily debug what is going on. If you could make a barebones project that has the behavior you're observing, or, if you don't mind me checking out your project, I could do use it as well.

**Comment by EddieK31** [comment]
Basically Joey, I download the Mac OS X zip file from this address (http://phantomjs.org/download.html) and add the phantomjs file that is in the bin directory in the path of my project.  In the project I use 

var execFile = require('child_process').execFile;
execFile(file2Execute,params,options,callback);

The file will not execute, if I replace the extracted file that is created with an original copy it will execute just fine.  I will try to create a simple project, and send it along.

I am doing this on a Windows 10 machine, but I have also tried it on a Mac directly and have the same results.

On 8/19/2016 10:34:07 AM, Joey <notifications@github.com> wrote:
It looks like the copy operation I use from here [https://docs.python.org/2/library/shutil.html#shutil.copytree] is already supposed to keep file attributes.
A simple project would help a lot so I can see exactly how you are running the application and I can easily debug what is going on. If you could make a barebones project that has the behavior you're observing, or, if you don't mind me checking out your project, I could do use it as well.

**Comment by EddieK31** [comment]
Here is a simple project.  You will need to have NW on your machine (I have been using 0.15.4), but I am sure that isn't an issue.  
Also because the zip file was to large I had to remove the PhantomJS binaries (http://phantomjs.org/download.html), you will have to download the binaries for both the Mac and Windows and place them in the appropriate folders in the Phantom directory.

Let me know if you need anything else, thanks for taking a look at this.
On 8/18/2016 2:37:55 PM, Joey <notifications@github.com> wrote:
Would you be able to bundle a little sample project that showcases the behaviour you are seeing?

**Comment by jyapayne** [comment]
It looks like I didn't get the attachment. Thanks for putting together a sample project!

**Comment by EddieK31** [comment]
Maybe because it was a zip file, just change this one to a zip and let me know.
On 8/19/2016 2:48:43 PM, Joey <notifications@github.com> wrote:
It looks like I didn't get the attachment. Thanks for putting together a sample project!

**Comment by jyapayne** [comment]
I think you have to send it via github itself and not email. I don't think attachments go through via email.

**Comment by EddieK31** [comment]
[W2ESample.zip](https://github.com/jyapayne/Web2Executable/files/427874/W2ESample.zip)

**Comment by jyapayne** [comment]
Interesting. When I run your provided project after downloading phantomjs and exporting on a Mac, the file permissions are preserved just fine, as expected. It looks like when you export on Windows and try to run it on a Mac, there is problems. I just tried it and had the same issue as you. Unfortunately, this is an issue with Windows itself. Windows, as you probably know, doesn't have the same robust file attribute system that Unix OSes do.

It seems there [isn't a way](http://stackoverflow.com/questions/13185364/how-to-assign-execute-permission-to-a-sh-file-in-windows-to-be-executed-in-linu) (that I know of) to copy the file on Windows such that it will still be executable on Mac, since Windows doesn't know about Mac's file attributes.

**Comment by EddieK31** [comment]
I will try it on the Mac from start to finish and see if I get the same results.
On 8/19/2016 3:32:47 PM, Joey <notifications@github.com> wrote:
Interesting. When I run your provided project after downloading phantomjs and exporting on a Mac, the file permissions are preserved just fine, as expected. It looks like when you export on Windows and try to run it on a Mac, there is problems. I just tried it and had the same issue as you. Unfortunately, this is an issue with Windows itself. Windows, as you probably know, doesn't have the same robust file attribute system that Unix OSes do.
It seems there isn't a way [http://stackoverflow.com/questions/13185364/how-to-assign-execute-permission-to-a-sh-file-in-windows-to-be-executed-in-linu] (that I know of) to copy the file on Windows such that it will still be executable on Mac, since Windows doesn't know about Mac's file attributes.

**Comment by EddieK31** [comment]
I just tried it on my Mac.  Download the files and built, then run.  It does not work.  Here is a screen shot of the messages and the files.  Notice that the one on right is the original downloaded one and the one on the right is the one that is extracted when running the app.

![mac](https://cloud.githubusercontent.com/assets/20583681/17825585/b550788a-6626-11e6-9c4a-e6e39c5b8bb7.png)

**Comment by jyapayne** [comment]
Interesting. I'm using the same phantomjs version. Which version of Web2Exe are you using?

**Comment by EddieK31** [comment]
v0.5.1b

**Comment by jyapayne** [comment]
Ah. It seems as though having the project zipped is the culprit. If you check "Uncompressed Folder" in compression settings, the phantomjs file should work. Something with Python's ZipFile implementation is to blame. I'll take a look and figure it out :)

**Comment by EddieK31** [comment]
Cool.  Thanks.

**Comment by jyapayne** [comment]
I guess I was wrong. If I manually extract the zip created by Web2Exe, the phantomjs executable is still executable by Mac OSX. I think the problem then lies with NW.js's extraction when it runs. You should file an issue on the NW.js page for this issue. As a workaround, just use the uncompressed folder option.

**Comment by EddieK31** [comment]
Thanks for working thru this will me.  I will use the uncompressed folder option.  Not sure if I could give a good enough explanation to file an issue on the NW.js page.  I might give it a try when I have more time.

Thanks again.

**Comment by jyapayne** [comment]
You're welcome! If you do file an issue, please link it to this one. I'm going to close this since it's an NW.js issue.
