### ISSUE TITLE
Packing options Enchancement

### ISSUE THREAD

**Issue by EthraZa** [jyapayne/Web2Executable#16]
Web2Executable zip the hole project into one big packed file right? But it still add some libraries and the pak file along side the executable, so we need to pack it all to be able to delivery.
I see 2 options that would greatly enchance how Web2Executable act to make it more of a deploying tool.

1- An option to exclude some directories/files from being packed into the executable and let this ones unpacked alongside the executable and libraries files.
 When running the app, 
path.dirname(process.mainModule.filename); give you the temporary unpacked path,
path.dirname(process.execPath); give you the installation path

2- The level of compression applyed to the packed executable file, if possible.

**Comment by jyapayne** [comment]
This should be mitigated now with the option to export to an uncompressed folder.
