### ISSUE TITLE
Empty relative output directory when outside the project directory

### ISSUE THREAD

**Issue by hexus** [jyapayne/Web2Executable#164]
When using a relative output directory path such as `..\bin` or `../bin`, with or without trailing slashes on Windows, the export directory is empty, other than an empty folder with the project name.

Using `bin` by itself, or an absolute path, works fine.

By the way, fantastic project. Such an amazingly useful tool. :+1:

**Comment by jyapayne** [comment]
Thanks for filing this issue! I'm a bit busy these days but I'll get to it when I have time.

Thank you for using it and contributing :)

**Comment by hexus** [comment]
Thank you kindly! :grin:
