### ISSUE TITLE
Default nw.js after compression.

### ISSUE THREAD

**Issue by wisniewski94** [jyapayne/Web2Executable#165]
Hello :)

I have noticed that my app is not working on most of machines. Switching between version and SDK doesn't change anything. Compressed app works on my main pc (win7 x64) but it loads default nw.js on win10 x64 and win7 x32. I want my app to work compressed even on winXP so deploying program just for one system is not a solution.

I have theory that it doesn't work becouse of module nodemailer. Old versions of my app which were compressed without module work fine. 

There is no problem with uncompressed folders. But I would like to secure my work. Thanks!

**Comment by jyapayne** [comment]
Can you try exporting with an older version of NW.js? The latest ones have some issues. Try NW.js 0.16.1 and see if it helps at all. I'm looking into some other issues with the newer versions of NW.js, so hopefully I can figure this out.

**Comment by jyapayne** [comment]
It looks like right now any compression level other that 0 makes Windows dlls not work. For right now, I'm not sure why that is (something to do with how the DLLs are built on the latest versions of NW.js), but you can disable compression (which only compresses DLLs) and uncheck the "Uncompressed folder" option. This will zip your code onto the executable itself and be harder for someone to find. Web2Exe doesn't secure your code at the moment, so I recommend using a minifyer on your code.

**Comment by wisniewski94** [comment]
I'm compressing my app on 0 lvl because of start-up time. And "Uncompressed folder" checkbox was always unchecked. This compressed application works only on my main PC (it doesn't matter on which machine I used web2executable). If I choose Uncompressed folder it works on all computers.

I will try to find what possibly causes this problem by trial-and-error method but I'm not expecting any breaktrough since nature of this problem is beyond my level. Until then I will just compress my source code.

**Comment by jyapayne** [comment]
That's very interesting. Then there must be something with your code that's causing an issue. It could be node dependencies, but it's hard to say without your source directory. If you don't mind, you could email me a link to your source so that I can debug the project.

**Comment by jyapayne** [comment]
For future reference, this bug was caused because of Windows' 255 char limit on the file path length.
