### ISSUE TITLE
Request to change export dir structure

### ISSUE THREAD

**Issue by Forecaster** [jyapayne/Web2Executable#172]
(I hit enter after writing the title...)

Currently Web2Exe exports the built application into a structure like this:

>output_dir/{output_name_pattern}/{target_system-arch}/
>eg:
>output_dir/cmdrs_log_continued-0.1/linux-x64/

This, for me at least, makes archiving builds a little fiddly, since the actual app files are a directory removed from the dir with the app name pattern. I would like the output to look like this instead:

>output_dir/{output_name_pattern}-{target_system-arch}/
>eg:
>output_dir/cmdrs_log_continued-0.1-linux-x64/

This would allow me to more quickly archive the applications, because now both the application name and the system+architecture are going to automatically be put in the archive name.

Currently I need to re-arrange and rename the dirs to get this effect, or manually name the archive.

Perhaps the system and architecture could be presented as a pattern option instead, for example %(target) or similar, and remove the previously used subdir?

**Comment by jyapayne** [comment]
That's a good idea. I think it's a useful thing to be able to choose how to use the system and architecture. It wouldn't be too hard to add an option like this, so I'll add it when I have some more free time.

**Comment by Forecaster** [comment]
System can also have a long and a short version, such as
%(system) => windows
%(sys) => win

Not really necessary, but sometimes it's nice to keep filenames as short as possible
