### ISSUE TITLE
NW.js version list is empty and "Update" button doesn't work

### ISSUE THREAD

**Issue by vfxBoat** [jyapayne/Web2Executable#175]
Hi!

I'm using Web2Executable v0.5.4b in OSX 10.10.5

The NW.js version list is empty and pressing the "Update" button doesn't do anything at all.

In fact, pressing it multiples times crashes the app.

**Comment by jyapayne** [comment]
Yep, it looks like that occurs if the version file is empty. As a workaround until I fix it, if you open `~/Library/Application Support/Web2Executable/files/nw-versions.txt` and add `0.19.0` to it, the version fetching should work.
