### ISSUE TITLE
nw.js not properly downloading (macOS 10.12.2, web2exe 0.6.0b)

### ISSUE THREAD

**Issue by mixvio** [jyapayne/Web2Executable#178]
I've discovered that nw.js doesn't want to properly download when I attempt to make builds now; it doesn't matter which version I pick, or whether or not force download is checked, but the progress bar rapidly appears to be downloading files but the zips themselves are immediately deleted afterward and as a result the project doesn't build properly, or at all. I'm not sure if it's an issue with how web2exe is accessing the nw.js files or what, but it unfortunately is preventing me from making any builds at all.

**Comment by Forecaster** [comment]
It sounds like your anti virus is deleting them, probably because of a false positive associated with nw.is because of people using it to make malware

**Comment by mixvio** [comment]
As the title says I'm on macOS so there's no antivirus installed. It also worked previously and has only begun failing to download properly recently (I only noticed it yesterday).

This is also not the final build version — I have noticed that executable builds are sometimes deleted by Windows users' antivirus software. This is the nw.js code itself being downloaded prior to building the project. Given the way the web2exe dialog is behaving, it leads me to believe there's some sort of connection issue — downloads complete instantly, whereas in the past they took a fair amount of time to finish.

**Comment by jyapayne** [comment]
@mixvio You were correct with the connection issue. Apparently, the maintainer of NW.js switched the download urls from HTTP to HTTPS. Accounting for that, everything seems to be working. I'll upload a fix build as soon as I can :)

**Comment by mixvio** [comment]
Great thanks for the quick fix — is it only going into the cmd version for OS X though? I use the GUI one personally.

**Comment by jyapayne** [comment]
:) It just takes a little bit of time to build!

**Comment by wisniewski94** [comment]
I have 0.6.1b and bug still occurs.
