### ISSUE TITLE
Project exported sayed "Done", but empty

### ISSUE THREAD

**Issue by Nabu0001** [jyapayne/Web2Executable#182]
The software seems to consider job's done, but output folder is empty. I tried Web2Executable because Electrify does not work too, but I'd like to use an alternative to NodeWebkit.

As for Electrify, I tested everything with file permissions etc...

Does not work.

**Comment by wisniewski94** [comment]
1. What version do you use?
2. Try exporting two times - sometimes it gets buggy don't know why and in most cases it's related to few errors such as wrong output settings / problem with loading nw.js src files etc.

**Comment by jyapayne** [comment]
@Nabu0001 Yes, which version do you use? In the latest release I tried to fix this issue. As for Electrify, the code is unfortunately out of sync with this repo and does not have all of the enhancements that I have made since it is a lesser-used project and I don't have as much time these days to maintain both.

**Comment by wisniewski94** [comment]
@jyapayne just noticed that I also got this problem. Web2Exe doesn't download nw.js src files (.zip) and that's why it finishes before it do anything.

**Comment by Nabu0001** [comment]
@jyapayne, I'm using the latest 0.6.1b windows binary release.
@wisniewski94, I'll try this and see, thanks !

**Comment by jyapayne** [comment]
You are both on Windows? I'll check it out when I get the chance!

**Comment by wisniewski94** [comment]
Yes, tried on win7 and win10.

**Comment by jyapayne** [comment]
I can't seem to reproduce the issue. Can you post the exact steps you are following? Here are mine:

1. Clear downloads folder
2. Open a project
3. Select Windows-x64 in Export settings
4. Select NW.js 0.20.1 in Download settings
5. Click export
6. Download starts as normal and exports as normal

**Comment by Arti3DPlayer** [comment]
same on windows 10. I downloaded project that works and built with web2exe on mac, but on windows seems issue with download nw.js. I get empty folder.

**Comment by keshav2609** [comment]
Same issue help please

**Comment by Arti3DPlayer** [comment]
version 0.6.0 do not have this bug

**Comment by jyapayne** [comment]
Sorry guys, I haven't had much time lately. I'll commit to looking at this tonight. @Arti3DPlayer thank you for the information. This means that Windows 10 is having some sort of issues with the https calls. Hopefully I can figure this out tonight!

**Comment by jyapayne** [comment]
Hey everyone! It looks like I was right about the https calls. Windows doesn't like them for some reason when Web2Exe runs as a bundle, but it works fine if run from my dev environment. I've updated the downloads for the Web2Exe 0.6.1b on the releases page. Hopefully this fixes the issue for you guys! Let me know!

**Comment by keshav2609** [comment]
Thanks mate work fine :-)
