### ISSUE TITLE
OSX - 0.6.3b - error logging seems to be disabled

### ISSUE THREAD

**Issue by Blatman** [jyapayne/Web2Executable#187]
Just been using W2E and got the old problem of empty build folders which of course turned out to be modules in node_modules not being uninstalled correctly however I did notice that the W2E error log was absent - normally this sort of problem does create errors. I tried W2E 0.6.1b and earlier and they all have the logging. I tried running W2E with a corrupt package.json file and again no error log was produced by this version (unless of course it has moved).
Normally found in Users/username/Library/Application Support/Web2Executable/files/error.log

OSX 10.11.6
Building app with nwjs 0.20.3

Cheers

**Comment by jyapayne** [comment]
That's interesting. Something must have happened in the last couple of releases. Taking a look!
