### ISSUE TITLE
OSX - w2e 0.6.4b icon paths hardcoded in manifest - built app won't launch

### ISSUE THREAD

**Issue by Blatman** [jyapayne/Web2Executable#188]
OSX 10.11.6  El Capitan
NWjs 0.20.3-osx

Using 0.6.4b the generated builds are not launching - the problem appears to be hard-coded icon paths in the package.json (should be stripped to relative paths) - tried 0.5.1b and all was OK.
Have attached screenshots and the test project to assist.

[iconbuildbug.zip](https://github.com/jyapayne/Web2Executable/files/854508/iconbuildbug.zip)

**Comment by jyapayne** [comment]
Ah, something is going wrong with file copying. So here's the issue: if icons are outside the project directory (where the package.json exists) Web2Exe *should* copy them to that folder and replace the absolute path with the new path. The reason is that NW.js can't see anything outside that folder. For some reason, it looks like this behavior is not happening anymore.

As a workaround, you could copy those files inside your "Blank" folder and reference them in Web2Exe.

**Comment by Blatman** [comment]
Right then - going bananas here but have found that putting the files in the Blank folder didn't work so well but if I just build it as normal and then edit the icon references in the generated app package the app will work fine (a hassle tho!).  When I was trying the earlier builds of W2E to test I was being tripped up by the modified package.json file - came right when I restored the original package.json file.  Also wondering why the webexe_settings are still in the package.json when there is now a separate web2exe.json file produced. Note: retried the 0.6.3b build and it was OK so the issue appears to be with the 0.6.4b build.

**Comment by jyapayne** [comment]
The webexe_settings should only be in the package.json if they were in there already before (when you were exporting with older versions it would have been added).
I'll try to have this fixed as soon as I can. It's probably creating a lot of grief for others as well.

**Comment by Blatman** [comment]
Thanks Joey - can't check though - no W2E for Mac build in the 0.6.5 downloads.
I will wait in case the downloads are taking a while to update.
Cheers.

**Comment by jyapayne** [comment]
Hey man, sorry about that. I had issues building on my Mac last night. I'll put it up when I get home!

**Comment by jyapayne** [comment]
Should be up :)
