### ISSUE TITLE
Pass Arguments to compiled Application

### ISSUE THREAD

**Issue by qstarx** [jyapayne/Web2Executable#194]
There is a problem with Arguments passed  to the compiled App on startup.
If the Argument is a valid file path the App crashes and does not pass the argument to the App.
Therefore it is not possible to open the App with an associated file extension

**Comment by jyapayne** [comment]
I need a bit more information to determine your problem. What architecture are you exporting to? And which arguments are you trying to pass?

**Comment by qstarx** [comment]
My actual build tests ar linux-x64 and windows-x64.
My App can read an input file passed by commandline parameter. That works fine if App is started with nw

    nw ~/ppadmin ~/test.txt

the compiled App runs fine without Arguments. But trying to start with the file Option the App crashes

    ~/ppadmin/output/ppadmin/linux-x64/ppadmin ~/test.txt

The Problem seems to be that the argument is processed and expected to contain some valid code:

    (function (exports, require, module, __filename, __dirname) { 12ew wed
                                                              ^^^
    SyntaxError: Invalid or unexpected token
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:567:28)
    at Object.Module._extensions..js (module.js:610:10)
    at Module.load (module.js:512:32)
    at tryModuleLoad (module.js:471:12)
    at Function.Module._load (module.js:463:3)
    at Module.runMain (module.js:647:10)
    at run (bootstrap_node.js:433:7)
    at startup (bootstrap_node.js:163:9)

Because if I pass a dummy Argument like

    ~/ppadmin/output/ppadmin/linux-x64/ppadmin 12345

the arg is passed to my App and catched by my error handler. But as soon as it is a valid file path, it does not work. Is there any File open handler during initialisation? How can it be overidden?

**Comment by qstarx** [comment]
The problem was solved using NW.js version higher 0.21.4
The issue I had was with version 0.21.3
