### ISSUE TITLE
Support for "chromium-args"?

### ISSUE THREAD

**Issue by MarcFowler** [jyapayne/Web2Executable#20]
It seems that whenever I have a "chromium-args" parameter included in my package.json file, it gets stripped out when Web2Executable runs.

Example package.json:

```
{
    "webexe_settings": {
        "linux-x32": false, 
        "download_dir": "/Applications/Web2Executable.app/Contents/MacOS", 
        "windows": false, 
        "mac": true, 
        "nw_version": "0.11.5", 
        "force_download": false, 
        "linux-x64": false
    }, 
    "description": "MyDemo", 
    "name": "MyDemo", 
    "nodejs": true, 
    "single-instance": true, 
    "webkit": {
        "page-cache": false, 
        "java": false, 
        "plugin": false
    }, 
    "window": {
        "fullscreen": false, 
        "resizable": false, 
        "title": "MyDemo", 
        "always-on-top": false, 
        "frame": false, 
        "show": false, 
        "kiosk": false, 
        "height": 500, 
        "exe_icon": "", 
        "width": 800, 
        "as_desktop": false, 
        "visible": true, 
        "position": "", 
        "show_in_taskbar": false, 
        "mac_app_icon": "", 
        "transparent": true, 
        "toolbar": false, 
        "icon": "icon.png"
    }, 
    "version": "0.1.0", 
    "keywords": [], 
    "main": "index.html", 
    "node-main": "",
    "chromium-args": "--disable-gpu --force-cpu-draw"
}
```

Can we add support for this parameter, both leaving it in the package.json file and to actually include it when running the app?

**Comment by jyapayne** [comment]
Hey Marc,

Thanks for pointing out this issue. If you edit the json file before Web2Exe runs, your options will stay in tact. So you can use that as a work around. If you edit the json while Web2Exe is running, it will overwrite any options. 

I will add support for this option and a few other options when I get the chance.

Cheers!

**Comment by jyapayne** [comment]
Hey Marc,

I've added the option and updated the builds. I also added some other options that were missing. Let me know if this is good for you.

Cheers!

**Comment by MarcFowler** [comment]
That's awesome! Thank you very much! :)
