### ISSUE TITLE
Show version of prebuilt binary

### ISSUE THREAD

**Issue by MarxGames** [jyapayne/Web2Executable#21]
Currently there is no way to tell which version of prebuilt binary I'm using. Add it either to here:
http://puu.sh/ephDN/a5e18c6c9d.png

or somewhere here(better):
http://puu.sh/ephFX/35d3ba3dd7.png

**Comment by jyapayne** [comment]
Yeah, that's a good idea actually. I'll attempt to put it in both places.

Cheers!

**Comment by jyapayne** [comment]
This should be in the latest builds. 

Closing.
