### ISSUE TITLE
Window transparency for irregular shapes

### ISSUE THREAD

**Issue by dariuszsikorski** [jyapayne/Web2Executable#22]
Hello, Node Webkit supports transparent window since v0.11.2 version. It would be very useful to have [x][set transparent window] checkbox for giving windows or widgets a custom shape instead of square block.

Good Luck in development of Web2Executable :)

**Comment by jyapayne** [comment]
Hey :) 

This option already exists in the Window Options section. It's the last option in the bottom right hand corner (labeled simply as "Transparent:"). It's in the newest version and I think it's what you are looking for :)

**Comment by dariuszsikorski** [comment]
Ugh, still can't find it...
That's how the Web2Exe looks on my OS

http://www.evernote.com/shard/s244/sh/8d9d616e-0006-4157-8ee1-7b428ca362d0/846b0829c6c1ec4c03f284cf56d2cbd5

By the way Node-Webkit has just been renamed to NWJS ;)

**Comment by jyapayne** [comment]
Ah, thanks for the info :)

You have to download the latest version, which is [0.1.12b](http://www.mediafire.com/download/vbpn8auennmit7a/Web2ExeWin-v0.1.12b.zip). 

Older versions don't have it, as I added it pretty recently.

Cheers!
