### ISSUE TITLE
Doesnt work - windows v0.1.13b

### ISSUE THREAD

**Issue by MarxGames** [jyapayne/Web2Executable#23]
I've selected all of the output formats and only such folders are created:
linux-x32
windows-x32
windows-x64

linux-x32 contains place_holder.txt and a 30kb file named after my project
windows-x32 only contains place_holder.txt
windows-x64 contains place_holder.txt and a 30kb .exe named after my project

**Comment by jyapayne** [comment]
Yes, as it seems, exporting is doing something weird when downloading to many items at once. If you do each individually, it should work. (You may have to force download if you get no output or an error.)

I will fix this ASAP.

**Comment by jyapayne** [comment]
Hey @MarxGames,
I think I've fixed the issue. Download the latest version in the readme and you should be able to export all at once.

Cheers!
