### ISSUE TITLE
move to nw.js

### ISSUE THREAD

**Issue by aolko** [jyapayne/Web2Executable#24]
Will you move to a newer [**nw.js**](http://nwjs.io)?

**Comment by jyapayne** [comment]
Already did :) Is something not working?

**Comment by aolko** [comment]
Haven't had a chance to try, actually. Btw, how about modifying the window a bit?

**Comment by jyapayne** [comment]
Modifying it how?

**Comment by aolko** [comment]
make it like this ![window](http://i.imgur.com/3vkv3om.png)
