### ISSUE TITLE
libudev version problem on linux

### ISSUE THREAD

**Issue by onbscr** [jyapayne/Web2Executable#25]
error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory

until this is fixed in node-webkit you could work around it for ubuntu unicorn et al by replacing 'libudev.so.0' in the binary file with 'libudev.so.1'. 
I know that this is not a clean way to go, but it works meanwhile.

sed -i 's/\x75\x64\x65\x76\x2E\x73\x6F\x2E\x30/\x75\x64\x65\x76\x2E\x73\x6F\x2E\x31/g' <appname>

(I got it from somwhere in the net, it's not my invention)

**Comment by jyapayne** [comment]
Yeah, I'm aware of this issue. I'll put a note in the readme that links to this page: https://github.com/nwjs/nw.js/wiki/The-solution-of-lacking-libudev.so.0
