### ISSUE TITLE
nwsnapshot

### ISSUE THREAD

**Issue by ncd76** [jyapayne/Web2Executable#26]
Hi

I got the build working perfectly apart from when I add a .bin file using nwsnapshot.exe ("snapshot": "code.bin" in the package.json file)

The app runs fine after I add code.bin to the build folder - I can add this in my console app that does all the packaging but just a heads up that it looks like its not copying the .bin file it over.

Thx :+1:

**Comment by jyapayne** [comment]
Cool, thanks for pointing that out. I'll get it fixed as soon as I can.

**Comment by jyapayne** [comment]
Alright Nigel, the bug should be fixed. Check out the new download on the readme and let me know how it goes. 

Cheers!
Joey

**Comment by ncd76** [comment]
Thanks!

**Comment by ncd76** [comment]
Hi Joey, sorry to re-open this one.

"snapshot": "app/code.bin" is in my 'package.json'
"snapshot": "code.bin" is in my 'app/package.json'

i seems I need both to test and build but that's no matter.

code.bin doesn't seem to end up in the build, copying the file across no longer works - would you like a 'hello world' sample?

Thanks,
Nigel

**Comment by jyapayne** [comment]
Yes, please do. I'll take a look at it when I get the chance!

**Comment by jyapayne** [comment]
Hey, could you send me that hello world sample?

**Comment by ncd76** [comment]
Hi Joey

Sorry about that, its been manic.

This is the app, it references the code.bin built with snapshot, I’ve included code.js in a folder outside the app directory structure. The app works well when you run nw.exe 

https://www.levelsoftware.co.uk/downloads/HelloWorldApp.zip

This is the built version which doesn’t run, it just closes, even if I include code.bin in the folder

https://www.levelsoftware.co.uk/downloads/HelloWorldBuild.zip

I’m just wondering if there are missing files or something?

Thanks for taking the time to look at this, cheers,

Nigel

**Comment by ncd76** [comment]
Is this format OK? I can redo if required.

**Comment by jyapayne** [comment]
Yes, this format is fine. I'm just a bit busy and haven't had a chance to fully debug the issue. I'll update this when I figure out what's going on.

Cheers!

**Comment by jyapayne** [comment]
This seems weird to me. I tried exporting to Linux and ran it on my Ubuntu distro, which seems to work fine. It seems as though the windows version is not working correctly. I'll file an issue with the nwjs github repo.

**Comment by ncd76** [comment]
Hi Joey

Interesting and OK thanks.

**Comment by jyapayne** [comment]
Closing due to it being an issue with NWJS.
