### ISSUE TITLE
Output Software not starting

### ISSUE THREAD

**Issue by 2braincells2go** [jyapayne/Web2Executable#27]
Greetz!

Been little while since I have worked with W2E and decided to get back to it:) All the older projects I created worked fine. BUT now the ones I try will not start up and display?

I can see the exe has started by going to my Win 7 task manager, but outputted software does not appear on my screen?

Any ideas what I am doing wrong?

FYI:

Downloaded file from http://www.mediafire.com/download/5l2zlfi67721d88/Web2ExeWin-v0.1.15b.zip. Start it up and version shown is v0.1.14b

Many thanks!

**Comment by jyapayne** [comment]
Hey! Welcome back!

The software version is actually 0.1.15b, I just forgot to update the build number :)

Your project not starting could be a few different things. What version of node WebKit are you using? Try out other versions to see if they work.

It also could be your settings. Could you send a screenshot of your settings with the project?

**Comment by 2braincells2go** [comment]
Thanks for reply.

I have tried 1.15 and 1.14 without success. Not sure what the heck is going on. Using same computer but time has passed...

Here is a screenshot of settings:

![2015-02-01_122614](https://cloud.githubusercontent.com/assets/2567500/5993206/fcf4fdea-aa0d-11e4-85de-a25e7b60d182.png)

**Comment by 2braincells2go** [comment]
Jut noticed the crazy in download location. Have no clue that happened there...

But corrected and still same issue. Three instances of exe appears when viewing task manager, but no start up of software.

![2015-02-01_123303](https://cloud.githubusercontent.com/assets/2567500/5993230/bec3a746-aa0e-11e4-851d-3e4171c062b5.png)

**Comment by jyapayne** [comment]
Can you try a different node WebKit version? (Other than 0.11.6?) Try 0.11.0 or 0.10.5 (make sure to untick windows-x64, as there are no downloads for x64 on lower versions.)

**Comment by jyapayne** [comment]
Hmm.. I tried the exact same project on W2E 0.1.15b with Win 7 and exported to windows-x32 and it worked. Are you trying to run the x64 or x32 version that is exported?

**Comment by jyapayne** [comment]
Wait! I think I found the issue. Please change the file path of the Main html file to be just: main.html.

It looks like there's a bug there.

**Comment by 2braincells2go** [comment]
Just tried 0.10.5 with x64 unticked. No change.

Tried all versions of compiled software on Win10 Tech Preview and same thing happens. Appears in task manger but no software starts up...

I downloaded the WIndows package at http://www.mediafire.com/download/5l2zlfi67721d88/Web2ExeWin-v0.1.15b.zip and I assume all the files needed to run are included?

**Comment by 2braincells2go** [comment]
That was it Joey! Changed to just main.html and started right up. Thanks man.

Is the bug on my end, something I am doing wrong?

Trying to get a software ready for school project and so, so glad back on track. Saved me:)

**Comment by jyapayne** [comment]
It's a bug on my end, so no need to worry. Windows paths are tricky to deal with! I'll update the build with a fix soon and I'll let you know when you can download it.

Cheers!

**Comment by 2braincells2go** [comment]
Not a problem, totally understand. Amazed the software creates all the different packages to begin with:)

Really appreciate your help. Got some kids math software to compile and really wanted to use W2E, makes so much easier for dis ole man...

Cheers!

**Comment by jyapayne** [comment]
You're very welcome :) I'm just glad you use it and get some value.

The new version is up on the Readme!

Cheers!
