### ISSUE TITLE
OSX gui binary not loading on Yosemite

### ISSUE THREAD

**Issue by tdgcummings** [jyapayne/Web2Executable#28]
Have been unable to open any of the OSX builds using Yosemite 10.10.2 or Mavericks.

The launcher attempts to launch then encounters a problem.

Have tested on MacPro and MacBook Air.

**Comment by jyapayne** [comment]
Hey!

Thanks for the info. It seems there was an issue with my build environment that was causing Mac builds to only work on 10.9 (my build OS).

I've updated the download for 0.1.16b, so please try to download and run it again and tell me how it goes. If you get an error, please paste it in a [pastebin](http://pastebin.com/) and send me the url.

Cheers,
Joey

**Comment by tdgcummings** [comment]
Have just tested on all the Mac systems I own and it works great!

Thanks Joey.
