### ISSUE TITLE
nw support

### ISSUE THREAD

**Issue by geoidesic** [jyapayne/Web2Executable#29]
Can this support nw (i.e. v 0.12.0) instead of nodewebkit?

**Comment by jyapayne** [comment]
I can look into supporting it. I was waiting until it became a bit more stable and was released. 

Thanks for the feature request!

**Comment by 2braincells2go** [comment]
Yes, please consider supporting nw.

Thanks much!

**Comment by mrmlnc** [comment]
+1

**Comment by jyapayne** [comment]
All in due time, my pretties. Will get it out as soon as I can!

**Comment by jyapayne** [comment]
Support is in the upload queue! See the readme shortly for a download link!
