### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by micc83** [jyapayne/Web2Executable#30]
Hello Joey, first all thank you for Web2Executable, it actually makes NW.js packaging process a breeze. I'm writing about your project and as i'm really not into python I'd like to have more informations about dependencies.
In the readme of the project you write that the following dependencies are needed for Web2Executable to work:
- Python
- Pyside
- PIL or PILLOW

However I've just tried it in a clean Mac OS X Yosemite and everything is working out of the box (even the icon for windows executable). So... are those dependencies already installed in Mac OS X or am I missing something?

**Comment by jyapayne** [comment]
Hey! :)

I'm glad to hear you're having a good time with my app :)

To address your question, I have some information. If you are using the prebuilt package, there are no dependencies. If you are using the github repo with Python, then you will need the dependencies that are mentioned. I suspect you are using the prebuilt package? If not, please correct me :)

I'll make a note in the read me to clarify.

**Comment by micc83** [comment]
I feel a bit dumb now but yes, off course I'm using the prebuilt package! So i can assume the same goes for the Windows and Linux prebuilt packages?

**Comment by jyapayne** [comment]
Never feel dumb for asking a question! It was a valid one. :)

And yes, you are correct. Although for the Linux package, I'm unsure as to whether or not it works on other distributions of Linux besides Ubuntu, since I haven't done any thorough tests in that regard.

**Comment by micc83** [comment]
Thank you so much Joey! You saved me a lot of headaches!
As I'm here I need to ask... how come haven't you implemented the customisation of the Application name and version on the plist file on Mac OS X ? It looks pretty trivial when compared to all that Web2Executable already does...

**Comment by jyapayne** [comment]
You're welcome :)

Haha, I didn't consider it, honestly. I'll try to put that in the next build. I'm on the move currently, traveling in NZ, but I'll update it whenever I get the chance :)

**Comment by micc83** [comment]
Thank you again! Do you want me to open an issue for that?

**Comment by jyapayne** [comment]
Sure :)
