### ISSUE TITLE
Update Info.plist when packaging for Mac OS X

### ISSUE THREAD

**Issue by micc83** [jyapayne/Web2Executable#31]
Hello Joey as per #30 I'm requesting to update `Info.plist` when packaging for Mac OS X customizing `BundleName`, `CFBundleShortVersionString` and `CFBundleVersion` with the data on the manifest file.
Thank you so much and good job again.

**Comment by Blatman** [comment]
+1
W2E very good so far and the Info.plist updating would be great - also since NWJS has a native Mac menu with About it automatically looks for Credits.html in parent folder of app.nw so it would be handy if W2E handled that file as well during packaging.

**Comment by jyapayne** [comment]
Thank you both for the feature request! I'll have to rewrite a portion of the GUI since the options are getting to be cluttered. This will likely take a while, but it will be easier to add things and it should look a whole lot cleaner. :)

**Comment by jyapayne** [comment]
Added support for this in the repo. It will be in the next build. I decided to fix some issues before building the new UI.

**Comment by micc83** [comment]
Thank you :+1:
