### ISSUE TITLE
"name" in manifest is wrong; Separate out App Name away from "name"

### ISSUE THREAD

**Issue by Martin-Pitt** [jyapayne/Web2Executable#32]
The "name" is being output with spaces which is incorrect, whereas I still want to be name the application with spaces, which is a different thing. Please separate out, this is both a bug (manifest spec isn't followed) as well as an enhancement ("name" manifest should be disconnected from real application name used on .exe / .app)

See: https://github.com/nwjs/nw.js/wiki/Manifest-format#name

Before Web2Executable my workflow of a manual build was as follows:

"name" in manifest would be like: "client_brand_some-project"
set the application name in the filesystem to: "Brand - Some Project"
I would also apply the same to the Window Title: "Brand - Some Project"

**Comment by jyapayne** [comment]
Hey Martin,

Thank you for the feature request/bug report :) 

You are absolutely right. I seemed to have missed that little section in the manifest about the name being lowercase with no spaces. Right now, I'm working on a redesign of the W2E GUI and will include this change in the new version. This will mainly update the aesthetics and provide a cleaner UI.

Cheers!

**Comment by jyapayne** [comment]
This has been fixed and will be in the next build.
