### ISSUE TITLE
Lack of Kiosk mode

### ISSUE THREAD

**Issue by Martin-Pitt** [jyapayne/Web2Executable#33]
I would love to have a kiosk mode setting.

Keep in mind there's some issues with [keyboard input and kiosk mode](https://github.com/nwjs/nw.js/issues/1440) (maybe offer [kiosk-like as per comment](https://github.com/nwjs/nw.js/issues/1440#issuecomment-47283154)) on mac & win.

Example Kiosk mode manifest
```json
{
	"name": "client_brand_project",
	"main": "app://./index.html",
	"window": {
		"title": "Fancy Window Title",
		"width": 1920,
		"height": 1080,
		"kiosk": true,
	}
}
```

Kiosk emulation hack (for working mouse/keyboard controls)
```json
{
	"name": "client_brand_project",
	"main": "app://./index.html",
	"window": {
		"title": "Fancy Window Title",
		"width": 1920,
		"height": 1080,
		"toolbar": false,
		"frame": false,
		"show": true,
		"kiosk": false,
		"fullscreen": false,
		"always-on-top": true,
		"resizable": false
	}
}
```

**Comment by jyapayne** [comment]
Hey Martin,

Thank you for the excellent feature request!

I am aware of the kiosk mode being absent. I left it out because of the instability I experienced when I used it. But with the new information you have provided, I can include it with the workaround in the new GUI redesign.

Cheers!

**Comment by jyapayne** [comment]
I'm not going to include the "kiosk emulation" mode in the GUI because you do have to add some javascript to make it work, which will confuse users. I will add the kiosk mode, though, in the next build.

**Comment by jyapayne** [comment]
Hah, nevermind. I was doing it wrong. I put a kiosk emulation section in the window settings and it works pretty well. Thanks for the suggestion!
