### ISSUE TITLE
Is there a way of having *some* files outside of the package?

### ISSUE THREAD

**Issue by TomCaserta** [jyapayne/Web2Executable#34]
Essentially I am currently using this to create a executable thats launched from a USB stick. As I need to be able to load some of the resources from the USB stick itself (to allow for images etc to be only included once per platform for space concerns). 

Is there any way of doing this? I have tried using the __dirname global however that supplies you with the temporary directory it creates.

**Comment by TomCaserta** [comment]
Aha figured this out, its pretty much the same as node-webkit, not sure why I didn't think to try that. 

`path.dirname( process.execPath );`

By default this gives you the path of the EXE etc, you may need to jump up a few directories to get to the place you want.

**Comment by jyapayne** [comment]
Yes, this was the same issue as #13.

I'll make a note in the readme as I should have done for #13. 

Cheers!

**Comment by TomCaserta** [comment]
Awesome, thanks for the really great easy to use application :+1:  :)

**Comment by jyapayne** [comment]
You're welcome :) Thank you for using it!

**Comment by karneaud** [comment]
To be clear on this

if i have 

c/path/folder/appname.exe

I can access c/path/include/styles.css

using `path.dir(process.exePath)/../includes/` absolute path?

can't i not use relative paths in files like `../../includes/styles' ?

**Comment by TomCaserta** [comment]
Unfortunately not, I cant remember why exactly, fairly certain it gives you the directory of some temporary folder that nw creates. You also need to check if your application is on a different OS as applications on Mac will lead to the executable inside of the .app folder (which means you have to jump up a few more directories/use a different location for your apps file storage.

**Comment by karneaud** [comment]
@TomCaserta 

Mac is not an issue as I'm developing for Windows. Here is my problem,


I need to develop an app that I can distribute as an exe to users however I need to be able to have content editable by user so i can't package the contents. I need to be able to allow this plus be able to keep source code from user. Online is not an option.

**Comment by TomCaserta** [comment]
Ah okay then yes, using:

`path.dir(process.exePath) + "/../includes/"` should work fine, was just giving a heads up just in case you was distributing to other OS's. I had the same concerns regarding having user editable content and having the source code "hidden" (not unobtainable to those that really want to try getting your applications source code). You just need to package the exe as normal and use the path to exe (see above snippet) to gain access to files that are outside relative to the exe itself.

**Comment by karneaud** [comment]
Thanks will try it.... just a bit of info found this http://kodeweave.sourceforge.net/ on the net...seems like a pretty interesting project. Hopes it can be integrated with node-webkit

**Comment by karneaud** [comment]
Question,

I develop on a Mac but do I need windows to export to EXE or can i create exe from mac?
