### ISSUE TITLE
PY Dependencies After Packaging

### ISSUE THREAD

**Issue by Synthetisoft** [jyapayne/Web2Executable#35]
Once I've packaged my project for an OS does the user have to install python or pyside before they can run the executable? I'm confused about that. If that's the case shouldn't the packaging come with pyside?

**Comment by Synthetisoft** [comment]
The instructions aren't very clear for how to create a binary for each OS that won't need any extra dependencies. It would be nice to know how to do this. I saw reference to prebuilt binaries but I don't know where they are or how to use them from start to finish. Also, if I use the binaries can I still change the icon?

**Comment by Synthetisoft** [comment]
One more thing on this issue. What about making installers? If there are dependencies can an installer install them first? Can py be bundled with the app packages? Also it wasn't clear about including files. Will it include all the files in my HTML and JS using relative locations?

**Comment by jyapayne** [comment]
Hi, thanks for the message.

There are no dependencies for the end user once built with Web2Exe. The dependencies are only for Web2Exe when running using python. The prebuilt binaries are downloadable from the read me.

**Comment by jyapayne** [comment]
For making an installer, that is completely up to you. Once the exe is built, you just have to make an installer for it. There are many applications to do this for you. All files in the project folder will be included recursively.
