### ISSUE TITLE
can't export , python error

### ISSUE THREAD

**Issue by rs324** [jyapayne/Web2Executable#36]
os : mac osx 10.9.5

im getting

Traceback (most recent call last):
  File "command_line.pyc", line 288, in download_file_with_error_handling
  File "/Users/rs324/Downloads/Web2Executable.app/Contents/Resources/main.py", line 393, in download_file
AttributeError: 'PySide.QtCore.QFile' object has no attribute 'error_string'

tried to export for windows only or windows and mac..

version :  0.1.16b

thanks.

**Comment by jyapayne** [comment]
I'll look at this when I get the chance. Thanks for filing the issue!

**Comment by jordancalder** [comment]
Also getting this same error. On a mac: 10.10.3

**Comment by jyapayne** [comment]
Do either one of you have write access to the folder that you are exporting to? There is a bug in there, but the reason you hit it is due to access issues of some kind.

Please try exporting to a folder that is maybe in your home folder or documents folder and see if that helps.

Cheers!

**Comment by jordancalder** [comment]
@jyapayne I've checked the permissions on the directory that I was writing to and everything looked okay there. I also tried writing to a dir in my documents folder. Still get the same error.

**Comment by jyapayne** [comment]
Yeah, I'm not sure about that... 
It might be an issue with Yosemite, but I unfortunately don't have a system with that OS, nor the time to update right now.

I'm uploading a new binary, which may have an effect on this issue, so please download 0.1.17b when it appears in the readme.

**Comment by jyapayne** [comment]
Does this issue still persist? If so, please reopen the bug.
