### ISSUE TITLE
Menubar app

### ISSUE THREAD

**Issue by geoidesic** [jyapayne/Web2Executable#38]
Node-webkit doesn't let one create a menubar application as far as I can tell.

I'm no MAC OS X dev, so this may be a barmey idea but... Is there any way that Web2Executable could wrap an app, so that it becomes a menubar app?

**Comment by jyapayne** [comment]
Hmm, I'm not sure if this is possible. The only information I have about it lies here: https://github.com/nwjs/nw.js/wiki/Window-menu

**Comment by geoidesic** [comment]
I found this clue: https://github.com/nwjs/nw.js/issues/3025. 
Maybe it's necessary to build the nw app as a menubar app, rather than trying to do it at the Web2Executable level?

**Comment by jyapayne** [comment]
What I gather from this is that you have to implement it yourself in your HTML file.

See here: https://github.com/nwjs/nw.js/blob/master/tests/manual_tests/custom_tray_menu/index.html

That javascript should do what you want. I don't have time right now to look at it more in depth, but if you feel unsatisfied, please reopen the issue and I'll take a more in depth look.

Cheers!
