### ISSUE TITLE
nwjs 12 Download Failed?

### ISSUE THREAD

**Issue by mscreenie** [jyapayne/Web2Executable#39]
I get this dialog when running Web2Exe on Windows 8.1, trying to download nwjs 12.00 Some versions download fine I tested version 11.5

![a](https://cloud.githubusercontent.com/assets/11147410/6597939/ff945ed0-c7f7-11e4-898a-46060e884ceb.png)

And even more confusing 11.6 doesn't even show..

![a](https://cloud.githubusercontent.com/assets/11147410/6598010/8d75993a-c7f8-11e4-8168-ef64b5a0edaa.PNG)

edit:

Things get a little stranger. The application randomly shows versions in the drop down. The latest it's showing of 11 branch is now 11.3

**Comment by jyapayne** [comment]
Hmm, it's strange about the versions not showing, but the reason 0.12.0 doesn't work is because I needed to add support for it. I'm uploading the changes to fix that soon, so hopefully it will resolve the issue.

Cheers!
