### ISSUE TITLE
Export successfully but nothing found.

### ISSUE THREAD

**Issue by NCNCNC** [jyapayne/Web2Executable#40]
I am using the newest version Web2Executable on OS X Yosemite 10.10. When I click on the export button, even though it says "Done export", I can't find anything under the output folder. What should I do?

**Comment by jyapayne** [comment]
Hey, thanks for using the app! 

I guess it depends on a few issues. Can I see your package.json and maybe get a description of your project folder?

**Comment by jyapayne** [comment]
There's also an issue where the folder doesn't exist when exporting to a different hard drive than the project is currently on, so make sure the export folder and the project folder are on the same disk.

**Comment by NCNCNC** [comment]
Here is my package.json and thank you for answering: 
```
{
  "name": "FeedMe",
  "main": "index.html",
  "node-main": "server.js",
  "version": "1.0.0",
  "window": {
    "title": "node-webkit demo",
    "toolbar": true,
    "frame": true,
    "width": 1200,
    "height": 700,
    "position": "mouse",
    "resizable": false
  },
  "node-remote": "<local>",
  "dependencies": {
    "body-parser": "^1.12.0",
    "express": "^4.11.2",
    "feedparser": "^0.19.2",
    "iconv": "^2.1.5",
    "nedb": "^1.1.1",
    "request": "^2.53.0"
  }
}
```

**Comment by NCNCNC** [comment]
Here is my project folder: 
![screen shot 2015-03-12 at 20 37 41](https://cloud.githubusercontent.com/assets/7675986/6617818/b047395a-c8f7-11e4-8ab6-6f6df05bde79.png)

**Comment by NCNCNC** [comment]
Oops...I just tried it again and it worked pretty well...
Thank you though.

**Comment by exitedprotek** [comment]
I had the same problem :/

Here is my package.json
```
{
    "webexe_settings": {
        "linux-x32": false, 
        "windows-x64": true, 
        "download_dir": "F:\\Logiciels\\Web2ExeWin\\files\\downloads", 
        "nw_compression_level": 5, 
        "mac-x32": false, 
        "windows-x32": true, 
        "mac-x64": false, 
        "nw_version": "0.12.0", 
        "force_download": false, 
        "linux-x64": false
    }, 
    "node-main": "app\\app.js", 
    "js-flags": "", 
    "description": "Launcher officiel d'Usinacraft", 
    "nodejs": true, 
    "chromium-args": "", 
    "additional_trust_anchors": "", 
    "maintainers": [
        {
            "web": "https://www.twitter.com/ExiTed_ProTeK", 
            "name": "ProTeK", 
            "email": "exitedprotek@gmail.com"
        }
    ], 
    "single-instance": true, 
    "inject-js-end": "", 
    "webkit": {
        "page-cache": false, 
        "java": true, 
        "plugin": false
    }, 
    "window": {
        "transparent": false, 
        "fullscreen": false, 
        "resizable": false, 
        "title": "Usinacraft Launcher", 
        "always-on-top": false, 
        "frame": true, 
        "height": 530, 
        "exe_icon": "app\\css\\images\\favicon.png", 
        "visible": true, 
        "as_desktop": true, 
        "position": "center", 
        "show_in_taskbar": true, 
        "mac_icon": "app\\css\\images\\favicon.png", 
        "width": 800, 
        "toolbar": false, 
        "icon": "app/css/images/favicon.png"
    }, 
    "user-agent": "", 
    "snapshot": "", 
    "version": "2.0.0", 
    "keywords": [
        "usinacraft", 
        "minecraft", 
        "mods", 
        "suisse", 
        "ProTeK"
    ], 
    "inject-js-start": "", 
    "node-remote": "", 
    "main": "index.html", 
    "dependencies": {
        "node-curl-download": "0.0.2", 
        "is-version-newer": "~1.0.2", 
        "many-file-hashes": "^0.4.1", 
        "mcms-node-localization": "0.0.3", 
        "fs-extra": "^0.16.4", 
        "memory-cache": "0.0.5", 
        "ds-cache": "0.0.7", 
        "async": "~0.9.0"
    }, 
    "name": "usinacraft-launcher"
}
```

And that's my project folder : 

![Folder](http://puu.sh/gxt0G/aeffbd1ad3.png)

**Comment by jyapayne** [comment]
Do you normally have all the nw.exe and other nodewebkit files in the folder while exporting? Could you try with those files removed?

**Comment by exitedprotek** [comment]
I tried and this time i had an empty folder "windows-x64" in the output folder

**Comment by jyapayne** [comment]
I noticed you have your main drive as your F drive. Is there a way you could move everything to your C drive and try again? There's a weird bug that I'm trying to track down that has to do with different hard drives.

**Comment by exitedprotek** [comment]
Ok I found the problem. If I chose the version 0.12 it crash so that if I chose the 0.11.5 version of it works!

**Comment by jyapayne** [comment]
Ah, yes. I'm working right now on 0.12.0 support. I'll update with a fix shortly.

**Comment by jyapayne** [comment]
Looks like this was caused because of 0.12.0 not being downloadable. Hopefully my new changes will fix this issue, which I'm uploading right now. The new downloads will be available in the readme shortly, so please download the new version and reopen this if the issue is still there.

Cheers!

**Comment by jyapayne** [comment]
See #47 for insight into the issue.
