### ISSUE TITLE
Why is PDF support not bundled.

### ISSUE THREAD

**Issue by bumstyla** [jyapayne/Web2Executable#43]
The PDF.dll is missing when i bundle an executable.

**Comment by jyapayne** [comment]
It will or will not be there depending on what version of NodeWebkit/NWJS you are using. I think pdf support was starting in v0.11.X, but I'm not sure. Which version are you exporting with?

**Comment by bumstyla** [comment]
Just found out that i was missing the --plugin flag. Sorry for the false alarm. 

Thanks for the great tool.

**Comment by jyapayne** [comment]
No worries. And you are most welcome :)
