### ISSUE TITLE
Feature - Debug Output

### ISSUE THREAD

**Issue by jyapayne** [jyapayne/Web2Executable#44]
From the wiki:

```
Could you create a verbose mode which will allow the user to get a high
level output of what is going on. 
Maybe a debug level would be helpful as well to show a full debug output.

I am having issues on my Linux box where the cmd program is failing silently
with no outputs created. I have no idea what the underlying issue is. With a
verbose and/or debug output I could make more 
progress narrowing in on the issue.
```

**Comment by jyapayne** [comment]
This is an excellent feature request and have been meaning to do this for quite a while. However, with the current design, it is quite difficult to add this. I'm working on a new UI that will have a different backend as well. I will take this basic feature into consideration while developing this new UI.

**Comment by JavaScriptDude** [comment]
Thanks for looking at this.

**Comment by jyapayne** [comment]
This will be in the next build.

**Comment by jyapayne** [comment]
--verbose option was added in the latest CMD build. Also, the error log gets more information now from the GUI.

**Comment by karneaud** [comment]
how do i access debugging on runtime?

**Comment by jyapayne** [comment]
You mean the developer tools? Enable the "Show Toolbar" option under the "Window Settings" tab. Then click the little three lined box in the upper right hand corner.

**Comment by KillerSquid** [comment]
How do we do this now that Show Toolbar has been removed from the Windows Settings tab?  I added "toolbar":true to my manifest but still not seeing it.
Thanks.

**Comment by Forecaster** [comment]
@karneaud The sdk version had the debug options, the regular version does not. The toolbar no longer exists in either.

**Comment by jyapayne** [comment]
You must use the "SDK build" in the download settings. This build of NW.js will allow you to debug your app and should not be used for production. You can access the console using the F12 key or ⌘+⌥+i on Mac as specified [here](http://docs.nwjs.io/en/latest/For%20Users/Debugging%20with%20DevTools/)

**Comment by KillerSquid** [comment]
Thanks Joey- worked like a charm.  You're a champ.  Thank you for keeping this project going and being so quick to respond.
