### ISSUE TITLE
Do not overwrite package.json

### ISSUE THREAD

**Issue by JavaScriptDude** [jyapayne/Web2Executable#46]
When using your tool, it overwrites the users package.json with your own. This can cause issues with users not expecting this functionality and if they are not using SVC, they may loose data. Is there a way to consider using a different name for your package file so the users package.json is left intact?

**Comment by jyapayne** [comment]
It's true that the package.json is overwritten, however, all original options from the original package.json are retained. I read in the existing package.json, put some extra fields for my app, and write the package.json with both options.

I can put a note in the readme about this modification if you'd like.

**Comment by JavaScriptDude** [comment]
Thanks. I did see some odd issues with the new package.json blocking my app from running nw directly after your mods. I'll see if I can troubleshoot what the gaps are and update you.

Maybe you can consider creating a copy of the users original package.json calling it package.json_orig or something like that so as not to freak out the n00b's who are not using some form of SVC.

**Comment by jyapayne** [comment]
Alright, that seems reasonable.

**Comment by jerone** [comment]
All tools that use an JSON file for storing and retrieving data are using there own file. E.g. NPM is using `package.json`, bower is using `bower.json` and NuGet is using `project.json`. I know NW is using the same `package.json`, but what about using your own file to not override existing JSON files?

**Comment by jyapayne** [comment]
The reason I use the package.json is because I'm simply passing options from the GUI to NWJS. I could use my own, but then I'd just have to overwrite the package.json file with my file anyways, and that makes things unnecessarily complicated.

**Comment by jyapayne** [comment]
I've decided against this. Implementing it introduces lots of complexities and makes the code confusing.
