### ISSUE TITLE
New Feature: Package as single executable

### ISSUE THREAD

**Issue by JavaScriptDude** [jyapayne/Web2Executable#48]
Could you consider adding a feature to package as a single executable as per [nw.js instructions: Making an executable file out of a .nw file](https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps#step-2b-alternative-way---making-an-executable-file-out-of-a-nw-file).

Packaging as a single executable is a snappy way of distributing an app out to customers.

**Comment by jyapayne** [comment]
That's how my application works. It packs everything into an executable. I don't see what the issue is.

**Comment by JavaScriptDude** [comment]
Darn. You are right. Pardon my ignorance. I thought that the single executable just was one file but I saw a bunch. I then read the Node Webkit page and it sounds like the nw.pak is required for node webkit. 

Please feel free to close this ticket.

**Comment by jyapayne** [comment]
No worries! Kind of shattered my reality a bit :P
