### ISSUE TITLE
Latest NW isn't latest in versions list

### ISSUE THREAD

**Issue by jerone** [jyapayne/Web2Executable#49]
The latest version from NW is v0.12.0. But in the [versions list](https://github.com/jyapayne/Web2Executable/blob/master/files/nw-versions.txt) that version is on the fifth place. RC & Alpha versions are lower then the latest released version v0.12.0.

**Comment by jyapayne** [comment]
Yes, this has been bugging me as well. I use a library to filter and sort versions that doesn't really support rc1 and alpha extensions. I'll try to come up with my own that supports all types.

**Comment by jerone** [comment]
Python right? https://github.com/keleshev/version

**Comment by jyapayne** [comment]
Nice. That should work nicely :) Thanks for the search. I'll put it in the next build!

**Comment by jyapayne** [comment]
Build is up!
