### ISSUE TITLE
Toggle Fullscreen (Feature Request)

### ISSUE THREAD

**Issue by jdoleary** [jyapayne/Web2Executable#50]
I can see that there is a checkbox for starting the executable in full screen, but there does not seem to be a way to toggle between windowed and full screen.
F-11 and Alt-Enter do not work.

**Comment by jyapayne** [comment]
You'd have to do that in nodejs. There's nothing I can do from my side, but look here for more info: https://github.com/nwjs/nw.js/wiki/Window#windowtogglefullscreen
