### ISSUE TITLE
can't run on mac os x 10.10

### ISSUE THREAD

**Issue by zhaowweny** [jyapayne/Web2Executable#51]
this app can't run on mac os x 10.0, when I click to run it, it show a error dialog containing open console and terminal, error info are below:
![qq20150425-1 2x](https://cloud.githubusercontent.com/assets/4287088/7333168/9d8266b6-eb96-11e4-992c-9f0ac641240d.png)

**Comment by jyapayne** [comment]
There's some missing information from that error that I need. Can you get me the full line for "ImportError: dlopen(..."?

**Comment by jyapayne** [comment]
I think I fixed it. Can you try the download again? I replaced the file, so you should just be able to download from the same link.

**Comment by zhaowweny** [comment]
ok,It can work now! Thanks four your contribution, I can easily package my app for all platforms with perfect settings!

**Comment by jyapayne** [comment]
Cool! You're welcome :)
