### ISSUE TITLE
Support generating a .desktop file for Linux

### ISSUE THREAD

**Issue by Montoya** [jyapayne/Web2Executable#52]
nw.js documentation mentions creating a .desktop file for Linux distribution: 
https://github.com/nwjs/nw.js/wiki/Icons

This allows supporting an icon to be used on the desktop, among other things. 

Any chance of W2E supporting this?

**Comment by jyapayne** [comment]
Yes, this is definitely possible. It's not that hard of a change for me to add, so when I get to making the next build, I'll definitely put this in. Thanks for the request :)

**Comment by Montoya** [comment]
:tada:

**Comment by jyapayne** [comment]
I put this in the latest build. Right now, it will pre-generate a .desktop file with your project information in it. You'll of course have to edit it if you are  going to be installing it somewhere else.
