### ISSUE TITLE
Mac 64 does not launch current directory

### ISSUE THREAD

**Issue by Kikketer** [jyapayne/Web2Executable#53]
So I have an application that has been using this tool quite well for some time.  Suddenly today when I did some updates to my application produced .app file simply launches the default NW.js window (the one with a toolbar and says NW.js inside).
![screen shot 2015-05-06 at 5 15 28 pm](https://cloud.githubusercontent.com/assets/958042/7504930/8dac6860-f413-11e4-82bc-c63d083fe72e.png)

I looked at the generated package.json files and they are identical (minus the version number I updated).  The nwjs executable inside the .app package appears to be identical as well.  If I launch the nwjs inside the app package directly it displays the same NW.js window.  If I do the same to my previous version, it loads up correctly.

I changed nothing in the web2executable GUI.

The application launches correctly when I use the command line ".../nwjs ." (while in the application directory).  Any ideas what would be causing this?

**Comment by jyapayne** [comment]
I can't really say without seeing the specific project. Would you be able to send me your project folder as a zip file to see if I can reproduce the error?

**Comment by Kikketer** [comment]
I sent a private email to you with the project.  Any help would be greatly appreciated!

**Comment by jyapayne** [comment]
Hopefully my fix works for you. Let me know if it doesn't.

**Comment by Kikketer** [comment]
The fix worked!  Thank you so much, it's great to see responsive support on GitHub.

**Comment by Kikketer** [comment]
Well I was a little premature when saying it worked.  The windows version (32bit) is having the same issue.  Can you apply this fix for the windows output as well?

**Comment by jyapayne** [comment]
That's interesting. The fix should work for all platforms. Let me do some
digging.

**Comment by Kikketer** [comment]
Thanks, let me know if you need the project again.

**Comment by Kikketer** [comment]
The issue was not web2executable.  It was windows's inability to parse long directory structures inside karma.  Lesson 1: windows sucks, Lesson 2: tests suck... :)
