### ISSUE TITLE
Single exe installer

### ISSUE THREAD

**Issue by alexcroox** [jyapayne/Web2Executable#56]
Would be great for this to build a single appName.exe Windows installer file that extracts it to the appropriate Program Files (x64 or not) for the user. Avoids the user forgetting where the hell they extracted that cool program they downloaded last month :)

**Comment by jyapayne** [comment]
It's going to happen eventually, just some kinks to work out like administrator privileges and persistent user data.


Thanks Alex :)

**Comment by 2braincells2go** [comment]
This is a great idea as long as it is an "option". We use a third party installer and very happy with the functions of it.

Cheers!

**Comment by jyapayne** [comment]
Of course. It will be an option to download, along with the "run from anywhere" version.

**Comment by jyapayne** [comment]
It has been done!

**Comment by 2braincells2go** [comment]
My bad, thought we were talking about adding function to W2E to create completed package installer, not an installer for W2E itself.

What happens when you get old, lol.

BTW, great job on new W2E GUI interface!

Cheers

**Comment by jyapayne** [comment]
Maybe you can get an extra brain cell so you have 3 instead of 2. 50% increase! ;)

Now that you mention it, maybe that is what Alex meant :0 If that's the case, I don't think it's possible to build an installer from the GUI itself.

And thanks for the praise :) Glad to hear you like it.

**Comment by 2braincells2go** [comment]
LOL, good one Joey. At my age extra braincell would go long ways:)

It is mostly I read / understood wrong.

Yep, GUI is great.

**Comment by Montoya** [comment]
Hi @2braincells2go, what 3rd party installer do you use? I haven't gone down the route of creating a windows installer for my app yet but I need to.

**Comment by jyapayne** [comment]
Ah, so you were looking for the installer for the built exe. I use a tool called NSIS, but there's also a tool called Inno Setup that other people like as well. They're both kinda technical but very useful.

**Comment by 2braincells2go** [comment]
Hey Montoya!

I mainly use http://www.installpackbuilder.com/ and love it. Does have a learning curve but even free version is packed with features.

Sometime I use Inno Setup as Joey mentioned. My nephew made a video on using (for total beginner if I recall) https://www.youtube.com/watch?v=UH1Cta3a7yA

Hope that helps.

Woody

**Comment by alexcroox** [comment]
Hi @jyapayne thank you for the installer! Unfortunately I can't get the README linked Windows 2.4b build to load, see screenshot: http://al3x.me/azpG/d

**Comment by alexcroox** [comment]
The event log is:

Activation context generation failed for "C:\Users\IEUser\Desktop\Web2Exe.exe". Dependent Assembly Microsoft.VC90.MFC,processorArchitecture="x86",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8" could not be found. Please use sxstrace.exe for detailed diagnosis. 

I'm guessing your build is 64bit and my OS X Virtual Machine is only 32bit?

**Comment by alexcroox** [comment]
OK the fix was to install Microsoft Visual C++ 2008 from https://www.microsoft.com/en-us/download/details.aspx?id=29

**Comment by alexcroox** [comment]
Spoke to soon the export option just creates the single credits.html file and nothing else inside of app-name\windows-x32\nwjs-v0.12.1-win-ia32

**Comment by jyapayne** [comment]
Alex, is there anything in the error log? It's located in C:\Users\<username>\AppData\Local\Web2Exe\Web2Exe\error.log.

**Comment by alexcroox** [comment]
I'm seeing a lot of hardcoded references to user "Joey"?

```ERROR      2015-05-18 06:57:36,081 command_line.py: 71 my_excepthook - Traceback (most recent call last):
  File "<string>", line 50, in run
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\command_line", line 555, in extract_files
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\command_line", line 190, in extract
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\zipfile", line 1028, in extract
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\zipfile", line 1083, in _extract_member
IOError: [Errno 13] Permission denied: 'files\\windows-x32\\nwjs-v0.12.1-win-ia32\\d3dcompiler_47.dll'

Copying files to \\VBOXSVR\5rsync\app
INFO       2015-05-18 06:57:36,108 command_line.py: 809 copy_files_to_project_folder - Copying files to \\VBOXSVR\5rsync\app
Generating package.json...
INFO       2015-05-18 06:57:36,108 command_line.py: 440 generate_json - Generating package.json...
['Traceback (most recent call last):\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 701, in make_output_dirs\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 597, in replace_icon_in_exe\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\pepy.pe", line 1152, in __init__\n', 'PEFormatError: File is not a proper portable executable formatted file!\n']
ERROR      2015-05-18 06:57:41,296 command_line.py: 730 make_output_dirs - ['Traceback (most recent call last):\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 701, in make_output_dirs\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 597, in replace_icon_in_exe\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\pepy.pe", line 1152, in __init__\n', 'PEFormatError: File is not a proper portable executable formatted file!\n']
```

**Comment by jyapayne** [comment]
You can safely ignore those hard coded references. Those are created by pyinstaller, which is what I use to package the application. They're useful for debugging on my side of things, since pyinstaller replicates my local file system.

But anyways, it just looks like I didn't properly convert over all of the references to the local files, so you get permissions errors. I'll put a fix in for that right away.

**Comment by jyapayne** [comment]
Alright, it should be fixed. Download the Setup.zip again and it should be worked out. I'll also add automatic installation of the visual studio runtime later based on your trial and error.

**Comment by alexcroox** [comment]
Excuse my ignorance where is the Setup.zip file in this repo? I noticed the pre-builts in the README haven't been updated.

**Comment by alexcroox** [comment]
OK so I think you updated the remote file and therefore no need for README link change.

Anyway all is working OK now, although I don't see any options for making this single exe installer?

**Comment by jyapayne** [comment]
Yeah, you are correct.

I said above that I misunderstood your request and thought you wanted Web2Exe to have an installer, which is what I did. I also said that it's not possible (at least as far as I can tell) to put your actual request in the build process. You'll have to use some third party creation tool.

**Comment by alexcroox** [comment]
Ahhh I see! Sorry for the confusion!

**Comment by alexcroox** [comment]
For anyone else looking for a simple solution, the quick start version here was super simple and did everything I needed:

http://www.jrsoftware.org/isdl.php#qsp
