### ISSUE TITLE
Auto Updater (for generated app)

### ISSUE THREAD

**Issue by Kikketer** [jyapayne/Web2Executable#57]
Feature request:
I create new versions of my application every other week.  I could probably write something up in my app to check for the new version and download/install it.  But wanted to propose it for this project.

Some option like "what url to check".  Perhaps that URL needs to simply return a version number of which it would compare to the package.json version number and download and replace automatically.

The hurdle I see when doing it myself would be that I would need to fire up a second instance (the updater instance) while the other files get replaced.  Since this updater would be mainly the same across most applications, it may be cool to see it as a checkbox in the GUI with a "url to check" field.

Keep up the good work!

**Comment by jyapayne** [comment]
Unfortunately, this is not something I have control over. Exporting an application merely wraps your existing code an puts it in an executable format. 

I do have a suggestion on how to do this, though. Most modern applications these days don't update files "on the fly". They download the files to a temporary directory, close the main application, and then copy over the new files with some additional updater app, like you said. There's a npm package that might do most of what you need, but I'm unable to say how it will work with my current packaging system.

The repo link is: https://github.com/edjafarov/node-webkit-updater

Let me know how it goes and maybe I can provide some assistance or information to help you out.
