### ISSUE TITLE
12.2 and future updates?

### ISSUE THREAD

**Issue by mscreenie** [jyapayne/Web2Executable#58]
seems like the app takes a while to catch up even after clicking update list when an update is released from nwjs.

I tried replacing the downloaded file with an update and it will not build completely.

12.2 is available too and not showing up in the app, thanks.

**Comment by jyapayne** [comment]
It should be available. What version of the app are you using and on what platform? The current version I have up (0.2.4b) should automatically get the versions from [here](https://raw.githubusercontent.com/nwjs/nw.js/master/CHANGELOG.md).

**Comment by mscreenie** [comment]
12.2 , with 2.4b. Should I delete its temporary files? Do you know where they are located?

**Comment by jyapayne** [comment]
My bad. By platform I meant Windows, Mac or Linux.

The data files are in:

   Windows: C:/Users/<username>/AppData/Local/Web2Executable/Web2Executable/
   Mac: /Users/<username>/Library/Application Support/Web2Executable
   Linux: /home/<username>/.local/share/Web2Executable/

There should be the option to select the version from the Download Settings tab. If it's not there, that means something is going wrong with the retrieval. When you open the application, does it say "Done getting versions."? Also, is there anything in the files/error.log file (relative to one of the above data paths)?

**Comment by mscreenie** [comment]
Cheers thanks for your help. I'm running Windows 8.1. Strangely when I run this application outside of a vm it works, though I had to still edit the versions file to include 12.2, it wouldn't show up even after I clicked update. 

All built now. Thanks for your hard work.

**Comment by jyapayne** [comment]
No problem :) Was there anything in the error.log? I'd like to debug what happened in case other people have the same issue.

**Comment by Blatman** [comment]
Yup, got the same issue with 0.2.4b on Mac - version updating fails although it says it's done.
Error log produced on start -
Getting versions...
INFO       2015-06-01 09:10:16,476 command_line.py: 365 get_versions - Getting versions...
Traceback (most recent call last):
  File "/Users/username/Desktop/Web2Executable 0.2.4b.app/Contents/Resources/main.py", line 50, in run
  File "command_line.pyc", line 366, in get_versions
  File "urllib2.pyc", line 154, in urlopen
  File "urllib2.pyc", line 431, in open
  File "urllib2.pyc", line 449, in _open
  File "urllib2.pyc", line 409, in _call_chain
  File "urllib2.pyc", line 1240, in https_open
  File "urllib2.pyc", line 1197, in do_open
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>

ERROR      2015-06-01 09:10:16,560 command_line.py: 71 my_excepthook - Traceback (most recent call last):
  File "/Users/username/Desktop/Web2Executable 0.2.4b.app/Contents/Resources/main.py", line 50, in run
  File "command_line.pyc", line 366, in get_versions
  File "urllib2.pyc", line 154, in urlopen
  File "urllib2.pyc", line 431, in open
  File "urllib2.pyc", line 449, in _open
  File "urllib2.pyc", line 409, in _call_chain
  File "urllib2.pyc", line 1240, in https_open
  File "urllib2.pyc", line 1197, in do_open
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>

Hope this helps,

Cheers.

**Comment by jyapayne** [comment]
This does help me, but unfortunately my build environment doesn't seem to be working at the moment. Yosemite is a tricky beast.

**Comment by Montoya** [comment]
I just opened nw-versions.txt and added the new versions (0.12.2 & 0.12.3) to the top to fix it. Not ideal of course :)

**Comment by jyapayne** [comment]
That URL bug should be fixed in the latest version (0.2.6b)
