### ISSUE TITLE
Question - Window Frame

### ISSUE THREAD

**Issue by pzolla** [jyapayne/Web2Executable#59]
I would like to remove the icon on the left side of the window frame when creating a Windows exe.  Can you advise how to go about that?

**Comment by jyapayne** [comment]
Pretty sure this isn't possible. I think it's just Windows' style of doing things. 

Just to be clear, you're talking about this icon, right?

![image](https://cloud.githubusercontent.com/assets/2645657/7784634/3de04dc8-012a-11e5-9999-1ec8e090b269.png)

**Comment by pzolla** [comment]
Yes


Sent by Outlook for Android





On Sat, May 23, 2015 at 8:01 AM -0700, "Joey" <notifications@github.com> wrote:
Pretty sure this isn't possible. I think it's just Windows' style of doing things.

Just to be clear, you're talking about this icon, right?

![image](https://cloud.githubusercontent.com/assets/2645657/7784634/3de04dc8-012a-11e5-9999-1ec8e090b269.png)


---

**Comment by jyapayne** [comment]
Yeah, it's not possible, to my knowledge. Unless you use a transparent png for the Windows icon. But then all other places will also have a transparent icon.

**Comment by pzolla** [comment]
So I am not sure - but does this address the issue?  
https://github.com/nwjs/nw.js/issues/1078

**Comment by jyapayne** [comment]
No, that's about changing the icon of the exe itself. Web2Exe already does that.

**Comment by pzolla** [comment]
I see.  Thanks.  I knew they were discussing the exe at one point but one of the posters was mentioning the 'title bar' and I was thinking maybe that was it.  Thanks for your help.  I will keep looking (its just I have see a few applications using nw.js that had custom)

In package.json

"window": {
    "title": "Title icon change ",
    "icon": "customIcon.png"
}

128x128 png
