### ISSUE TITLE
Setup File needed from web2exe

### ISSUE THREAD

**Issue by ScriptShellWriter** [jyapayne/Web2Executable#61]
Hi jyapane,

This is really awesome software. I'm very new in this platform. After export the files to windows-x32, there are number files are available. but how can we achieve only one exe file for windows setup.

I'm not getting any clue. Please suggest.

Thanks and Regards

**Comment by jyapayne** [comment]
To make a windows setup file, you'd have to use an external software like NSIS or InnoSetup. Web2Executable just packs everything together so that it's easy to do that.

**Comment by ScriptShellWriter** [comment]
thanks for your quick support.. This is really unbelievable. I love that..
Thanks again.. let me try.
regards

**Comment by mscreenie** [comment]
I find using InnoSetup with Web2Exe works beautifully, plus InnoSetup is matured and has good featuresets.
