### ISSUE TITLE
Support for Java based web apps?

### ISSUE THREAD

**Issue by demonzoo** [jyapayne/Web2Executable#62]
I'm trying to convert my Java web applications but didn't find any way to include the Java libraries and classes. And It looks like Web2Executable still doesn't support web applications that use Java as the back end.

I'd like to know if there's any workaround, thanks!

**Comment by jyapayne** [comment]
Using node-java, there might be a way to load java in node-webkit. See [here](https://github.com/joeferner/node-java#installation-node-webkit) and [here](https://github.com/joeferner/node-java/tree/master/testIntegration/webkit).

I don't have time right now to check if these things work, but if you get them to work, let me know.

**Comment by demonzoo** [comment]
Thanks, I actually slightly changed my client and send all the requests using web services. Now it works well even though the web services are on a remote server, because node.js doesn't have cross-domain issue. The Web2Executable is awesome. Great job!!!

**Comment by jyapayne** [comment]
Cool! Thank you and you're welcome! :)
