### ISSUE TITLE
Is there an option to maximize app window by default?

### ISSUE THREAD

**Issue by klevecoder** [jyapayne/Web2Executable#63]
Fullscreen is nice, but it's not an option for some cases, when you need to view taskbar and window buttons (minimize, close)

**Comment by jyapayne** [comment]
Unfortunately, nothing that I can do will be able to address that.

But, you can use javascript to achieve the same effect. See [this stackoverflow answer.](http://stackoverflow.com/questions/18423790/node-webkit-starting-maximized)
