### ISSUE TITLE
Fields uneditable on Mac - Yosemite

### ISSUE THREAD

**Issue by richpixel** [jyapayne/Web2Executable#65]
I'm on 10.10.3 Yosemite - when I run the GUI version of the app, it opens fine but none of the input fields can be edited. They appear to be grayed out.

**Comment by jyapayne** [comment]
You have to open a project first. Right now, a "project" is defined as a folder with an index.html file in it. All of the fields will become editable after a folder is chosen.

**Comment by richpixel** [comment]
Thanks for the quick reply! It works fine.

**Comment by jyapayne** [comment]
Cool :) Let me know if there are any other issues you have!
