### ISSUE TITLE
Running from command line

### ISSUE THREAD

**Issue by araad** [jyapayne/Web2Executable#66]
When running from command line, I would like it to read my config from package.json I tried passing the --output-dir and --package-json options, but it still requires me to type the --main option. This is what my command looks like:

web2exe-win.exe path\to\project --output-dir path\to\output --package-json

In the help section, it says that it will ignore all other optional arguments when --package-json is passed. Am I missing some arguments?

**Comment by jyapayne** [comment]
You'll pretty much need the --main option all the time. It's tricky to implement these kinds of things in the python option parser, since an argument can't really be "conditionally" required.

**Comment by jyapayne** [comment]
Closing based on inactivity. I tried to implement the --main option being optional. but it looks like it breaks a whole lot of GUI functionality.
