### ISSUE TITLE
path.dirname(process.execPath) return wrong path

### ISSUE THREAD

**Issue by tekrat** [jyapayne/Web2Executable#67]
I'm trying to get the path to dynamically load html file.  However when I try to build the path I get the path to executable, not path where the files are decompressed to.  Any suggestions?

var process = require('process');
var path = require('path');
var nwDir = path.dirname(process.execPath);

**Comment by jyapayne** [comment]
This is a problem that I've been trying to solve as well, but there doesn't seem to be a solution yet. You'll need to bring this issue up in the NW.js repo.
I'll update this issue if I find anything out.

**Comment by jyapayne** [comment]
There doesn't seem to be a solution yet. If this becomes available in future versions of NW.js, I will reopen this ticket.
