### ISSUE TITLE
Sounds issues?

### ISSUE THREAD

**Issue by fubeca6** [jyapayne/Web2Executable#68]
Using PhaserJS when I convert to win x32 exe, music is rendered but sound effects are not (only one audio track per screen?)

**Comment by jyapayne** [comment]
What audio format are the sound effects?

**Comment by fubeca6** [comment]
Music uses either ogg or wav, sfx are mp3 or wav

**Comment by jyapayne** [comment]
Yeah, mp3's will not play, so if any sound effects use that format, then you're out of luck. All the other formats are good, though. You could convert them to ogg and they should play fine.

**Comment by fubeca6** [comment]
Will do! Thanks for the help

**Comment by jyapayne** [comment]
No problem!
