### ISSUE TITLE
"Download failed: Not Found"

### ISSUE THREAD

**Issue by wildeyes** [jyapayne/Web2Executable#69]
Getting: Error! Download failed: Not Found.
What I did:
1. Download nw-samples, load up via open-project notification demo.
2. Select export to Windows-x32, 0.8.6 nw version, set camera.png icon from notification demo.
3. click export, wait until download progress bar gets to 100%, get an alert saying the above.

what do?

**Comment by jyapayne** [comment]
You'll probably need to select a newer version of nwjs, since older downloads get deprecated. They're still on there because they get automatically pulled from a text file that is not maintained by me. A version of 0.11.0 or higher should work.

**Comment by khurramraheel** [comment]
Can we specify a custom version of nw while building by locating its location?
