### ISSUE TITLE
how to chang node webkit app icon on windows

### ISSUE THREAD

**Issue by dragondjf** [jyapayne/Web2Executable#7]
how to change the .exe icon, not application's icon?

**Comment by jerone** [comment]
Did you find a solution for this issue? 
I have a custom icon for the executable but not in the top left corner of the window. 
Tested in Windows 7 & 8.1.

**Comment by jyapayne** [comment]
I have since updated the application to replace the icon automatically. The icon in the top left corner of the window is controlled by filling out the "Window Icon" field in the "Window Settings" section. Let me know if that works for you.

**Comment by jerone** [comment]
I just tested it on my own machine and the top left corner icon _doesn't_ show on Windows 7 64-bits here too.

This is my `package.json`: https://gist.github.com/jerone/2747c0fc42af865e3fdb
This is the image used as favicon: http://img.25pp.com/uploadfile/soft/images/2015/0121/20150121050758607.jpg

The `.exe` icon shows correctly in explorer and taskbar.

**Comment by jyapayne** [comment]
Looks like it might be an issue with how Node Webkit/NWJS processes jpg files. I tried using your icon, and it indeed did not work for the upper left hand icon, like you said. However, I converted it to a png, and all was well. I'll file a bug with nwjs about the issue.

**Comment by jerone** [comment]
> I'll file a bug with nwjs about the issue.

Thanks for doing that. I already replied with some more info. Just realized that this has nothing to do with Web2Executable, which only changes the `.exe` icon, right?

**Comment by jyapayne** [comment]
No problem :) Thanks for finding the issue, I always use png so I wouldn't have found it without you. 

You are correct about changing the exe icon, but Web2Exe does a bit more than that :)

**Comment by jerone** [comment]
> You are correct about changing the exe icon, but Web2Exe does a bit more than that :)

Of course, and doing a great job! I meant with the icon. :smile:

**Comment by jerone** [comment]
If they [still say no](https://github.com/nwjs/nw.js/issues/3317#issuecomment-91431750) to `.jpg` images, updating Web2Executable to disallow or even convert to other types would probably the best solution. What do you think...

**Comment by jyapayne** [comment]
That's true. Converting to PNG is a good solution. I'll implement that if jpg files are used.
