### ISSUE TITLE
Screen comes blank

### ISSUE THREAD

**Issue by zeeshanjan82** [jyapayne/Web2Executable#70]
When I am trying to create an .exe file using Web2Executable tool, I am able to export the application by providing the index.html file location but when I try to open the app.exe file which is generated I am only able to see the title being picked up from my index.html but the entire window in blank. How can I check the log or know why the window is coming as blank.

**Comment by jyapayne** [comment]
What are your settings that you are exporting with? Also, what is the contents of your index.html?

**Comment by zeeshanjan82** [comment]
I am only setting the main html index file path as well as the nodejs main server.js file path. Rest I just keep it to default. It is using Win32 as export option. I have a angularjs application with UI Router and NodeJS service with expressjs framework.

**Comment by jyapayne** [comment]
Hmm, without an example it's hard to diagnose what's going on. You could try enabling the "Window Settings -> Show Toolbar" option and look at the console window of the generated app to see if there are any errors loading your libraries.

**Comment by zeeshanjan82** [comment]
Thanks @jyapayne I tried enabling the 'Show Toolbar' option but still I am not able to find anything. I can just see a blank screen.
![blank](https://cloud.githubusercontent.com/assets/8342604/8830004/74484e62-30b7-11e5-8090-3962b3cf8b6f.png)

**Comment by zeeshanjan82** [comment]
One important point I would like to share is that I am having both angularjs and Nodejs as seperate applications. Actually angularjs application is requesting the views from nodejs service. I am not sure if that will really work out of the box in Web2Executable or not.

**Comment by jyapayne** [comment]
You must also open the console window by clicking the three line button in the upper right hand corner. This should let you know any errors.

Hmm, it should be able to work with angular js. There is an application here: https://github.com/arvindr21/nwk-ngApp

It uses angular js and seems to work fine. Note that in order to get that sample app to work, there might be a bug with a blank window icon, so you might need to set a dummy window icon in "Window Settings -> Window Icon" by browsing to an image.

**Comment by jyapayne** [comment]
The page I found that example on was: http://thejackalofjavascript.com/node-webkit-and-angularjs-a-moviestub-app/

Maybe that will help you to get the settings correct.

**Comment by jyapayne** [comment]
Did you have any luck figuring out why your app wasn't working?

**Comment by zeeshanjan82** [comment]
I have not been able to make use of Web2Executable as it has not worked for me. I have instead gone for the other approach where I zip all my files into an app.nw file and then use nw.exe to generate the .exe file. I am not sure if I am able to achieve it using .nw file then it should be very simple using Web2Executable. When I use Web2Executalbe I just see the default screen and nothing else. I am running Express.js which is referenced in my index.html file

**Comment by jyapayne** [comment]
That's what Web2Exe is doing behind the scenes. I'm taking the nw.exe and adding the app.nw file to it, just in a platform independent way. If it does work manually and not via my app, then something is up. Is there a chance that you could give me a copy of your project so that I could debug?

**Comment by zeeshanjan82** [comment]
thanks @jyapayne I will try to do that. I agree its something simple which is not working for Web2Exe.
