### ISSUE TITLE
[Windows] sxstrace.exe error

### ISSUE THREAD

**Issue by nighto** [jyapayne/Web2Executable#71]
When I try to open `Web2Exe.exe` on a Windows 7 machine I get a window with the following error:

> Error: The application has failed to start because the side by side configuration is incorrect please see the application event log or use the command line sxstrace.exe tool for more detail.

[This answer](http://answers.microsoft.com/en-us/windows/forum/windows_7-pictures/error-the-application-has-failed-to-start-because/df019c0d-746e-42d0-ad68-465e18e3f3ef) states that either Microsoft Visual C++ 2008 SP1 Redistributable Package or Microsoft Visual C++ 2010 Redistributable Package is missing. Can you tell me which one is required? It'd be good also to have it added on README.md file (I can propose a pull request when I know which version is needed).

Thanks in advance.

**Comment by jyapayne** [comment]
I'm not sure which one is required. I don't have a machine to test which one, but you could always try both of them and see which one makes the application work. Would you be able to do that?

And yes, it would be excellent to have this added to the Readme file, since there are probably a few people who get the same error as you. 

Thanks for letting me know about this issue :)

**Comment by 2braincells2go** [comment]
I would going with 2010 version for Windows 7. They both should work but only makes sense to use latest.

**Comment by jyapayne** [comment]
@2braincells2go You're probably right :)
@nighto Did you have any luck with either of them?

**Comment by 2braincells2go** [comment]
I do not have Microsoft Visual C++ 2008 SP1 Redistributable Package on my win 7 machine (except maybe some leftover DLL files) and all good here:)

Have Microsoft Visual C++ 2008 SP1 Redistributable Package on old Vista machine and no Microsoft Visual C++ 2010 Redistributable Package installed, all good on it:)

Cheers J!

**Comment by nighto** [comment]
Unfortunately I couldn't try yet, because I don't have administrative rights and I don't want to bother the sysadmins on my work.

I'll bugger they and install it when they can and I'll give back the results.

**Comment by TemaSM** [comment]
Today I had the same issue, but with Windows 10 Build 10240.
You can install hybrid Microsoft Visual C++ Redistributable. So, here is [link to Google Drive](https://goo.gl/QyptuR).
Just launch it and wait until setup will complete.
Hope this will help you :wink:

**Comment by jyapayne** [comment]
This looks like the issue is solved. Thanks @TemaSM for the link :) 

I put a note in the README that an installation of the redistributable package may be needed. Thanks for the info guys!
