### ISSUE TITLE
CLI urllib2 error

### ISSUE THREAD

**Issue by mnichols** [jyapayne/Web2Executable#74]
Hi I am trying to get started with the web2exe for MAC CLI and downloaded it today. When I run this...

```
./web2exe-mac --output-dir=/Users/mnichols/dev/pqls/dist/Darwin --package-json=/Users/mnichols/dev/pqls/apps/uprightly-ui/package.json --export-to=mac-x64 --main=/Users/mnichols/dev/pqls/apps/uprightly-ui/index.html --verbose /Users/mnichols/dev/pqls/apps/uprightly-ui
```

I get this ..

```
INFO       <string>.py: 424 load_package_json - Loading package.json
INFO       <string>.py: 862 download_file - Downloading file http://dl.nwjs.io/v0.12.0/node-webkit-v0.12.0-osx-x64.zip.
ERROR      <string>.py: 361 show_error - Traceback (most recent call last):
  File "<string>", line 412, in download_file_with_error_handling
  File "<string>", line 894, in download_file
  File "/Users/joey/Projects/Web2Executable/build/web2exe-mac/out00-PYZ.pyz/urllib2", line 154, in urlopen
  File "/Users/joey/Projects/Web2Executable/build/web2exe-mac/out00-PYZ.pyz/urllib2", line 429, in open
  File "/Users/joey/Projects/Web2Executable/build/web2exe-mac/out00-PYZ.pyz/urllib2", line 1135, in do_request_
TypeError: object of type 'SSLContext' has no len()

```

Just to see if I was missing some deps I did `pip install configobj && pip install Pillow` but they smell irrelevant.

Is this some kind of certificate problem (altho it is hitting nw over http...)?

**Comment by jyapayne** [comment]
I'm aware of this issue. However, I'm stuck not being able to fix it because of my build environment. I upgraded to Yosemite (my mistake) and tried to install the same packages in order to build W2E. However, it produces a binary which results in a segfault, and it won't work no matter what I try.

Until I get this figured out, there will be no updates to bugs :(

**Comment by mnichols** [comment]
Thanks for the response @jyapayne . I'm not a pythoner but am looking around to see if I can track it down

**Comment by mnichols** [comment]
Looking at the exception and your main.py, it looks like this isn't in your code, but rather the fact that we are hitting `http` and some validation inside the urllib2 is checking for an sslcontext, which of course there isnt one or at least should be skipped. 

I know there is talk at nwjs [here](https://github.com/nwjs/nw.js/issues/3228) about this problem with not exposing an ssl download.

I saw some SSLContext bugs reported using python 2.7.6, but I am using 2.7.10.

**Comment by jyapayne** [comment]
This is possibly fixed in the new version.

**Comment by jyapayne** [comment]
I'm going to mark this as closed since I haven't heard anyone else experience the same issue.
