### ISSUE TITLE
working with auto updates 

### ISSUE THREAD

**Issue by gladwinput** [jyapayne/Web2Executable#75]
Hello,

There is a great auto updater that relies on the use of nw-builder:
https://github.com/edjafarov/node-webkit-updater
Your awesome tool is much, much easier to use as it handles all the icon replacement etc. Would it be possible to create some kind of auto updater that interfaces with your tool, or are you aware of any way the known auto updater might be in some way compatible?

**Comment by jyapayne** [comment]
The tool you linked provides an example of how to use the auto updater with nw.js, which should work with my tool. If you open up https://github.com/edjafarov/node-webkit-updater/tree/master/app with W2Exe, you should be able to export a demo that works.

**Comment by gladwinput** [comment]
Oh I see, thank you very much! I'm a bit new to node so that escaped me. Thanks for replying, and go the tool its self. It is really excellent. I got auto update to work at your direction :)

**Comment by jyapayne** [comment]
Awesome, glad i could help :)
