### ISSUE TITLE
Mac Gui completely "locked" on Yosemite 10.10.5

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [jyapayne/Web2Executable#78]
The buttons are not working on v0.2.4b, not a single one. No interaction whatsoever possible. The only thing I can do is switching between the Setting tabs

**Comment by jyapayne** [comment]
Did you open a project folder? Buttons will be disabled until you open a folder with an index.html file.

**Comment by Karlheinzniebuhr** [comment]
It is inside the project folder, but all buttons are locked including the one to open the main html file

**Comment by jyapayne** [comment]
Can you send a screenshot and a list of steps that can reproduce the issue?

**Comment by Karlheinzniebuhr** [comment]
1. I put Web2Executable.app in the root folder of my project where the package.json is.
2. Double click on Web2Executable.app
3. Can't do anything, all inputs are locked (screenshots)

![image](https://cloud.githubusercontent.com/assets/5278928/9710001/c5bf7c88-5502-11e5-835e-822910c9999d.png)
![image](https://cloud.githubusercontent.com/assets/5278928/9710002/d15ccb54-5502-11e5-9cfc-d01e48540b0c.png)
![image](https://cloud.githubusercontent.com/assets/5278928/9710009/ea78ae6e-5502-11e5-834a-633632ce596f.png)

**Comment by jyapayne** [comment]
Ah, there's your problem. You're not supposed to put Web2Exe in the root of your project directory. Put it anywhere else, then from the menu, click File -> Open Project, and point it to your project folder.

**Comment by Karlheinzniebuhr** [comment]
Sorry for my silly mistake, thanks much!
