### ISSUE TITLE
Empty Output Folder

### ISSUE THREAD

**Issue by ken92** [jyapayne/Web2Executable#80]
I love this program and with small test versions of my code, it works perfectly to create a usable .exe file. Unfortunately, when I attempt to export my entire project, the output folder is completely blank.

My small test versions included the small amount of HTML needed to hold the GUI for my program along with all of the JS files -- six files total. The entire project contained all of these files along with the required node modules. I'm not sure exactly what the issue is, but if my node modules can't be packaged with the rest of my code, then the whole Web2Executable program is useless to me!

For reference, my node modules are fs, http, nw, request and webdriverjs

**Comment by jyapayne** [comment]
The node modules should be fine, since I've packaged node modules before. However, sometimes there is an issue with exporting that reports the export as successful, even though there is an error. 

Does anything show up in the error log? The error log is located in: C:\Users\<username>\AppData\Local\Web2Executable\Web2Executable\files\error.log

**Comment by ken92** [comment]
I cleared the log file and re-ran the program so I could present the fresh logs from trying to run it.

Getting versions...
INFO       2015-09-09 14:45:42,855 command_line.py: 365 get_versions - Getting versions...
Traceback (most recent call last):
  File "<string>", line 50, in run
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\command_line", line 377, in get_versions
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\semantic_version.base", line 75, in __init__
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\semantic_version.base", line 183, in parse
ValueError: Invalid empty version string: u''

ERROR      2015-09-09 14:45:44,229 command_line.py: 71 my_excepthook - Traceback (most recent call last):
  File "<string>", line 50, in run
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\command_line", line 377, in get_versions
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\semantic_version.base", line 75, in __init__
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\semantic_version.base", line 183, in parse
ValueError: Invalid empty version string: u''

Loading package.json
INFO       2015-09-09 14:45:47,361 command_line.py: 421 load_package_json - Loading package.json
Copying files to C:\Users\Eridan\Desktop\CEMSauto
INFO       2015-09-09 14:45:53,605 command_line.py: 809 copy_files_to_project_folder - Copying files to C:\Users\Eridan\Desktop\CEMSauto
Generating package.json...
INFO       2015-09-09 14:45:53,607 command_line.py: 440 generate_json - Generating package.json...
['Traceback (most recent call last):\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 629, in make_output_dirs\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\utils", line 71, in zip_files\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\zipfile", line 1118, in write\n', "WindowsError: [Error 3] The system cannot find the path specified: u'node_modules\\\\nw\\\\node_modules\\\\decompress\\\\node_modules\\\\vinyl-fs\\\\node_modules\\\\glob-stream\\\\node_modules\\\\unique-stream\\\\node_modules\\\\through2-filter\\\\node_modules\\\\through2\\\\node_modules\\\\readable-stream\\\\node_modules\\\\process-nextick-args'\n"]
ERROR      2015-09-09 14:45:54,505 command_line.py: 730 make_output_dirs - ['Traceback (most recent call last):\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 629, in make_output_dirs\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\utils", line 71, in zip_files\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\zipfile", line 1118, in write\n', "WindowsError: [Error 3] The system cannot find the path specified: u'node_modules\\\\nw\\\\node_modules\\\\decompress\\\\node_modules\\\\vinyl-fs\\\\node_modules\\\\glob-stream\\\\node_modules\\\\unique-stream\\\\node_modules\\\\through2-filter\\\\node_modules\\\\through2\\\\node_modules\\\\readable-stream\\\\node_modules\\\\process-nextick-args'\n"]
Traceback (most recent call last):
  File "<string>", line 50, in run
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\command_line", line 732, in make_output_dirs
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\shutil", line 252, in rmtree
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\shutil", line 250, in rmtree
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\eridan\\appdata\\local\\temp\\webexectemp\\test.nw'

ERROR      2015-09-09 14:45:54,523 command_line.py: 71 my_excepthook - Traceback (most recent call last):
  File "<string>", line 50, in run
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\command_line", line 732, in make_output_dirs
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\shutil", line 252, in rmtree
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\shutil", line 250, in rmtree
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\eridan\\appdata\\local\\temp\\webexectemp\\test.nw'

**Comment by jyapayne** [comment]
It looks like there are too many submodules inside the nw node package. Windows has a hard filepath limit of 255 characters. This means that you cannot access files that are more than 255 characters deep in a directory structure. I've seen this issue before, and the solution was to remove the offending files.

Is there a reason you need the nw package? Web2Exe uses NW.js under the hood to export the exe.

You can see the issue here: https://github.com/nodejs/node-v0.x-archive/issues/6960 and here: https://github.com/npm/npm/issues/3697 and here: https://github.com/npm/npm/issues/7768

**Comment by ken92** [comment]
Ahhh, ok. I was running into that issue with folder placement, too, but I wasn't sure if that would be the issue, here. I'll test it without nw and see how it goes, thanks!
