### ISSUE TITLE
Exporting app that runs as sudo

### ISSUE THREAD

**Issue by ryechus** [jyapayne/Web2Executable#81]
Hi,

Thanks for making this! How would I export an executable that runs node-webkit as sudo? For instance, if I was using the command line to run my nw instance I would do ```sudo nw ./```

**Comment by jyapayne** [comment]
:) You're welcome! Thanks for using it!

You could either run the application itself as sudo: `sudo ./exported_app` and it should run, or you could only require certain commands within your app to request sudo permissions (more work, but safer) as seen [here](http://stackoverflow.com/questions/25754602/sudo-command-node-webkit). You could also use the [sudo package](https://www.npmjs.com/package/sudo).

**Comment by jyapayne** [comment]
Did this help at all?

**Comment by ryechus** [comment]
It helped, but my app isn't laid out in a way where I can call different portions of code or services using sudo. Currently I run ```sudo nw ./``` and that runs a webkit app that then executes an express app. That express app has a few routes and those routes then call functions in the express app. One of the functions that gets called needs sudo privileges, but I haven't figured out how to give just *that* function privileges except for calling the entire app with sudo. I tried making a kick-off script of sorts, but that didn't really work well with nw.

**Comment by ryechus** [comment]
I actually did figure this out using one of the sudo apps that are available through npm.

**Comment by jyapayne** [comment]
Cool. Sorry I didn't respond to your last message. Been busy and it got lost under some emails.

Glad to hear you figured it out!
