### ISSUE TITLE
Gui won't Export if options are changed and package.json main is "http://..."

### ISSUE THREAD

**Issue by rafsoaken** [jyapayne/Web2Executable#82]
If I have a "main html file" package.json option "http://...." and load the project in the Gui, then the corresponding field under "App Settings" has a red border, but the Export still works (Button is not greyed out). If however I change another option, then the Gui apparently rechecks the validity of all the options and finds the "invalid" Main html file option and greys the Export button out.

It should not check "Main html file" validity, because it cannot anyways.

**Comment by jyapayne** [comment]
Unfortunately, you must have the local files in your project folder. Web2Exe doesn't support online files.

**Comment by rafsoaken** [comment]
I'm not sure you understood correcty. I have all my nwjs project files in a local folder. Only the main html file loaded by nwjs, given as option "main" in package.json is online. It builds fine on the command line, and it builds fine in the Gui if I dont change any options. 

Only if I change an option in the Gui, it then greys out the Export button. Does that make sense now?

**Comment by jyapayne** [comment]
Technically, giving a URL should not work at all. Web2Exe expects all files, including the main html file, to be on the disk you are building the app on. Is there a reason you need to use "http://..." instead of a local copy?

**Comment by rafsoaken** [comment]
Using a remote index.html works very well with web2exe - I need to iterate a lot on client feedback, so instead of redistributing the app everytime when I make a change, I can make changes to the index.html online and just send a reload event to the local app for the new version to become available.

I also use web2exe from the commandline now, and it works here without issues.

**Comment by rafsoaken** [comment]
Is it by design you don't want to allow URLs as 'main' nwjs option?

**Comment by jyapayne** [comment]
To be honest, I didn't expect this to be a use case :) In the future you might want to use [node-webkit-updater](https://www.npmjs.com/package/node-webkit-updater) for more complex updating.

I can easily update this to work for URLs in the GUI. However, I cannot update the Mac OS X version at this time, since the tools I used to build it are no longer working. Which platform do you use?

**Comment by rafsoaken** [comment]
I use Windows for distribution. I also looked at node-webkit-updater, but will decide on it at a later date. I'm not sure how much I can break if an update goes wrong. Corrupted zip file, bug in update code, typo, nwjs version incompat, etc? I don't want to be stuck with 200+ clients in limbo.. - all this is a non issue if you can just reload/restart the same app and have it download a fresh index.html version.

**Comment by jyapayne** [comment]
Can you try this version I whipped up?

http://www.mediafire.com/download/6nmp09ruxy62l72/Web2ExeWin-v0.2.5b-url.zip

**Comment by rafsoaken** [comment]
Thanks for improving this option - I tried it and it worked if the http:// path was already correct with a filename at the end.
However it seems to check on every keystroke, then gets slow and I had to restart it after a couple of changes to the url. Also it didn't take google as starting page, so I guess other url schemes don't work. Log says "http://www.google.com, does not exist". Also what happens if the remote url waits for a correct nwjs useragent, then you cannot verify it.

But it's an improvement, because if the file was requested ok, then I can change all the other options no problem! Thanks for working on this.

**Comment by jyapayne** [comment]
You're welcome :) 

I'm wondering if it's more useful for you to see that the url actually exists, or to see that it's in the proper format. If you are okay with having a simple url validation, I'll just do that to make it more simple.

**Comment by rafsoaken** [comment]
I think super simple url validation would be more useful than trying to actually fetch anything from the server. There could be too many reasons why atm the url cannot be fetched..
Cool for me!

**Comment by jyapayne** [comment]
I've updated the file at the link above with the new functionality. Try it out and hopefully it works for you :)

**Comment by jyapayne** [comment]
Should be good to go. Closing.
