### ISSUE TITLE
additional_trust_anchors don't work

### ISSUE THREAD

**Issue by CyberianIce** [jyapayne/Web2Executable#84]
There is a bug when placing additional_trust_anchors with this application. Either if You choose pem encoded file, or raw pem encoded string, this application is unable to parse nw.js package.json correctly according to manifest format. Unfortunately, this make Web2Executable unable to pack and distribute any app which use self-signed SSL/TLS. Problem can be easily solved by handling trust anchors as an array of strings (as they should be treated), and so enclose additional_trust_anchors array with square brackets (array elements with double quotes, comma separated)

This should work :)
"additional_trust_anchors": ["-----BEGIN CERTIFICATE-----XXX-----END CERTIFICATE-----"], 

But this won't work :(
"additional_trust_anchors": "-----BEGIN CERTIFICATE-----XXX-----END CERTIFICATE-----",

**Comment by jyapayne** [comment]
You are correct. However, I can only update this application on Windows right now. Which platform are you using to export?

**Comment by CyberianIce** [comment]
Linux/Windows. "--ignore-certificate-errors" as chromium arg may be temporary workaround, but it's not best security practice.

**Comment by jyapayne** [comment]
Alright. I'll try to come up with a quick version that allows comma delimited strings for the certificate :) Windows only, as stated above, though.

**Comment by jyapayne** [comment]
I believe I have fixed it. Test out the new version and let me know if all goes well :) http://www.mediafire.com/download/un39rt9ddq8jvol/Web2ExeWin-v0.2.6b.zip

**Comment by CyberianIce** [comment]
Nice, almost done! now it seems to work. However, as PEM encoded cert contain newline characters (\n), your parser should strip those newline chars in order to cert work properly (for now user must manually delete all newlines in additional_trust_anchor).

Second, in near future it would be nice to parse commas or empty spaces as array delimiters so more than one cert can be used.

About distant future, it would even better to insert PEM encoded certs as files instead of string (with open file dialog)...

Keep up good work & have fun!

**Comment by jyapayne** [comment]
Ah, I can do the newline parsing :) Commas are already parsed as delimiters, so you should be able to enter multiple. I realize the field is kind of small, so maybe opening the cert files would be better. I'll think up a way to make this a nice option.

Cheers!

**Comment by jyapayne** [comment]
@CyberianIce about the newlines, as seen [here](https://github.com/nwjs/nw.js/wiki/manifest-format#additional_trust_anchors), the newlines must be present. Anyways, though, I'm going to try to write a small widget that can handle multiple files for this field.

**Comment by CyberianIce** [comment]
You are correct, I just tested it now and it actually works fine with as without newlines :)
