### ISSUE TITLE
Triggering Chromium Arguments

### ISSUE THREAD

**Issue by karneaud** [jyapayne/Web2Executable#86]
Hi,

I'm developing a desktop app for windows 7 and I'm compiling the app with `Chromium Args` set to `--enable-file-cookies`

However, when running the app in windows 7 chromium seems to not have started with the argument options as inspector shows that the option is still disabled. 

the package.json has the option so I'm not sure what is the problem here

**Comment by jyapayne** [comment]
I don't think that option exists for chromium (which is what NW.js uses). The full list of chromium args is [here](http://peter.sh/experiments/chromium-command-line-switches/). I did a Ctrl-F to find "cookies" but no option containing that word could be found.

It looks like that flag was removed [a little while ago](https://codereview.chromium.org/976553002)

**Comment by CrandellWS** [comment]
This may help you https://github.com/nwjs/nw.js/wiki/Window#windowcookies if desired you could store info in any preferred way then use [remove](https://developer.chrome.com/extensions/cookies#method-remove) and [set](https://developer.chrome.com/extensions/cookies#method-set) as desired.

**Comment by karneaud** [comment]
I was wondering as one article says that chrome removed it...however another article was saying that it was simply disabled by default leaving us with the option to enable it if necessary

**Comment by jyapayne** [comment]
@karneaud Did our information help you? I'm closing this issue, but feel free to open it again if you have any related problems.
