### ISSUE TITLE
Load plugins

### ISSUE THREAD

**Issue by karneaud** [jyapayne/Web2Executable#87]
i have a question about the load plugins

are the plugins for nodejs? or chromium? I ask because I was wondering if the flash player is available with chromium or do i have to install it separately or included in the build

**Comment by jyapayne** [comment]
See [here](https://github.com/nwjs/nw.js/wiki/third-party-browser-plugins)

**Comment by karneaud** [comment]
Hmmm...thanks is it that i use the pepper or the npapi? and do use the .plugin or .dll? I'm building for a windows platform

**Comment by jyapayne** [comment]
You'll have to use the npapi, as NW.js does not support the Pepper plugins, as seen on the link I gave you. I believe you use the .plugin format. You might be able to use pepper flash .dll via the chromium arguments as seen [here](http://stackoverflow.com/questions/28110416/displaying-flash-files-in-a-node-webkit-app) (.so is the Unix equivalent of .dll)

**Comment by karneaud** [comment]
yeah i was just about to comment ...i wasn't sure what to do as I only had the pepper plugin. I'll try and find the other one

**Comment by 2braincells2go** [comment]
Wondering if anyone got flash working? Failing miserably here... Must be how I am try to setup unless it is hopeless?

**Comment by jyapayne** [comment]
Hey Woody, you have to use the npapi plugins, but I'm not sure where to find them, since chrome stopped using them. You might be able to find it by downloading a really old chrome version.

**Comment by 2braincells2go** [comment]
Hey Mr Joey! I am not sure have right plugins or even setup correctly so will continue my search of solution. Have spent hours reading info from search and on stackoverflow. Seems most have hacked together a solution by using pepperflash but, that is not legal to use and cannot have issues since using in school environment.

**Comment by 2braincells2go** [comment]
Oh man, my head is so sore.  Banged it on the desk and now the wall, huge bumps lol.

I have tried using info from https://github.com/nwjs/nw.js/wiki/third-party-browser-plugins and http://stackoverflow.com/questions/28110416/displaying-flash-files-in-a-node-webkit-app

Found the older npapi pepperflash here http://www.slimjet.com/chrome/google-chrome-old-version.php (in the slimjet browser as it still used npapi).

I have checked the "load plugins" box and placed pepperflash in project folder under the "plugins" directory.

I have tried entering "--ppapi-flash-path=plugins/libpepflashplayer.so --ppapi-flash-version=17.0.0.134" into the Chromium Args field, no luck.

Have tried for a month... Have lost track of attempts and pages viewed looking/trying info...

No luck and I give up. Always tell my kids to never give up and I normally do not but, I have been defeated. I surrender :)

If anyone ever gets flash working with the Web2Exe, would appreciate a ping.

**Comment by jyapayne** [comment]
Hey Woody!

I think I found a solution. Exporting with NW.js 0.13.X or higher, it seems like you can manually add the flash plugin without touching the chromium args field. From the google forum [here](https://groups.google.com/forum/#!topic/nwjs-general/j7eCY7YJVcQ), it looks like you can export the application using Web2Exe, then copy the pepflashplayer.dll AND the manifest.json file into a folder called "PepperFlash" in the same folder as the exported exe file. (You can get the manifest.json and the .dll from C:\Program Files\Google\Chrome\Application\<version>\PepperFlash if you install Google Chrome)

For this to work, you must delete the text you already have in the chromium args field. You also must download the appropriate version of Chrome for what you've exported. If you exported to Windows 64-bit, make sure you use the 64-bit path to get the pepper flash plugin and manifest file, or else it won't work. 

I've linked a sample exported project that works for me on Windows 7 64-bit. The project's contents itself is in the package.nw folder. I simply exported that project and copied my PepperFlash folder to be in the same directory as the exported exe.

[FlashTest Project](http://www.mediafire.com/download/3261drdj699admx/FlashTest.zip)

Hope it helps ease your bumps :)

**Comment by 2braincells2go** [comment]
Joey for President! Got my vote:)

Think it is going to work for me but for some reason the school virus scanner (webroot) is going bat sh*t crazy when downloading NW.js 0.13.X (any 13 or 14). Never has happened b4 and no issues at all with 12 or below. Looks like webroot thinks ffmpeg.dll in 13+ is rouge and we know it is not.

I will try this when they let me escape for my cell later this evening. After I try on my home desktop will report back.

Your a champ Joey!

**Comment by 2braincells2go** [comment]
Thought you may know... Quick question and if you do not know, will do my own search to find out.

Do the packaged apps require the ffmpeg.dll? Seems I recall trying to remove in past and caused issue even though my app had no requirements for the dll.

Can't wait to get home and try new build:)

**Comment by jyapayne** [comment]
I don't believe that ffmpeg.dll is required, but if you play any sounds it is most definitely needed. I removed it just fine for one of my apps :)

**Comment by 2braincells2go** [comment]
Thank you again Joey.

I can happily report that flash is working by following your info.

Only issue I have is my home version of Webroot is also reporting ffmpeg.dll as having virus then deleting it. Only happening on 13+ of NW.js. Understand not your issue, just passing on observation.

Cheers!

**Comment by 2braincells2go** [comment]
Just a note for you Joey:

Removing ffmpeg.dll in any of my latest app results in error (debug.log). The app will not start and debug.log shows:

[0421/100159:ERROR:main_dll_loader_win.cc(134)] Failed to load NW DLL from F:\Math Exercises\Export\mockflashtest\windows-x32\nw.dll: The specified module could not be found. (0x7E)

Placing ffmpeg.dll of course fixes.

Again just observation and thought it may help for future ref.

**Comment by jyapayne** [comment]
Ah, thanks Woody. I'll make a note of that :) I guess it changed recently.
