### ISSUE TITLE
How do I launch it?

### ISSUE THREAD

**Issue by TheSourceCodeTF2** [jyapayne/Web2Executable#89]
Hello, 

Sorry for this very nooby question, but I am very unsure how I am suppose to launch "How2Executable", as well on how to use it. I've tried looking at the F.A.Q., and a lot of other places, but sadly, I can't find guide or tutorial on how to open/use it. If anyone here could help out, I'd be most grateful.

Thanks for reading!

**Comment by jyapayne** [comment]
You mean how do you launch Web2Executable? What platform are you using (Windows, Mac, or Linux)? Also, can you describe the what you are doing currently that doesn't work?

**Comment by TheSourceCodeTF2** [comment]
Yep, I really have no clue how to launch it. 

And I am using a Windows.

As for describing what isn't working, I just don't know how to launch it. I'm not really good with this stuff, and just got into learning this kind of thing yesterday.

**Comment by jyapayne** [comment]
If you ran the installer, you should have a shortcut on your desktop that can launch it by double clicking. If you downloaded the zip file with the Web2Exe.exe, all you have to do is double click that and it will launch.

What version of Windows are you running? (Windows 7, 8, or 10?)

**Comment by TheSourceCodeTF2** [comment]
Ah, now I see. But looks like I have a real problem on my hands now. After I double-clicked the installer, something seems to pop up for a second, and immediately closes right after. Is this normal?

(I am running a Windows 7)

**Comment by jyapayne** [comment]
This is not normal. I'm thinking something is happening that is making W2E crash. Can you open up the log file and see if there is any information?

C:\Users<username>\AppData\Local\Web2Executable\Web2Executable\files\error.log

**Comment by jyapayne** [comment]
Was there anything useful in the log?

**Comment by jyapayne** [comment]
I'm closing this but you can reopen if the issue still persists.
