### ISSUE TITLE
Exported project app only runs nw.js app

### ISSUE THREAD

**Issue by srebling** [jyapayne/Web2Executable#92]
Project seems to export fine.  When I run the app, the nw.js app runs with the project name and that's all.
OSX 10.10.3
nw.js 0.12.3
Web2Exe 0.2.8b

**Comment by jyapayne** [comment]
It might be project specific. Would you be able to send me your project via email so I can test it? My email is jyapayne@gmail.com.

**Comment by jyapayne** [comment]
You may alternatively check/post your error log here to see if there is anything wrong. The error log is in /Users/<username>/Library/Application Support/Web2Executable/files/error.log

**Comment by srebling** [comment]
There's a ton of test logic in it.  I will simplify it and try again.  The actual app will be hard for you to run.  It uses node-opcua (http://node-opcua.github.io), which communicates tcp to various devices and sends data points to firebase.com.  Requires firebase login and connected devices to work.  Maybe too much for Web2Exe?

Thanks

On Nov 04, 2015, at 11:58 AM, Joey <notifications@github.com> wrote:

You may alternatively check/post your error log here to see if there is anything wrong. The error log is in /Users//Library/Application Support/Web2Executable/files/error.log

**Comment by jyapayne** [comment]
Can you post the error log and check the error console as I mentioned above?

**Comment by srebling** [comment]
Not much in the error log.

nw.js console displays nothing. Doesn't look like it's loading anything.


On Nov 04, 2015, at 12:12 PM, Joey <notifications@github.com> wrote:

Can you post the error log and check the error console as I mentioned above?
—
Reply to this email directly or view it on GitHub.


Getting versions...
INFO       2015-11-04 12:27:01,582 command_line.py: 374 get_versions - Getting versions...
Loading package.json
INFO       2015-11-04 12:27:04,288 command_line.py: 430 load_package_json - Loading package.json
Copying files to /Users/stevenebling/node-proj/node-opcua-bootstrap
INFO       2015-11-04 12:27:14,407 command_line.py: 833 copy_files_to_project_folder - Copying files to /Users/stevenebling/node-proj/node-opcua-bootstrap
Generating package.json...
INFO       2015-11-04 12:27:14,407 command_line.py: 449 generate_json - Generating package.json...
Copying files to /Users/stevenebling/node-proj/node-opcua-bootstrap
INFO       2015-11-04 12:29:19,619 command_line.py: 833 copy_files_to_project_folder - Copying files to /Users/stevenebling/node-proj/node-opcua-bootstrap
Generating package.json...
INFO       2015-11-04 12:29:19,619 command_line.py: 449 generate_json - Generating package.json...
Copying files to /Users/stevenebling/node-proj/node-opcua-bootstrap
INFO       2015-11-04 12:30:54,450 command_line.py: 833 copy_files_to_project_folder - Copying files to /Users/stevenebling/node-proj/node-opcua-bootstrap
Generating package.json...
INFO       2015-11-04 12:30:54,451 command_line.py: 449 generate_json - Generating package.json...

**Comment by jyapayne** [comment]
Hmm... Can you send your package.json file? I'd like to see what your settings are :)

**Comment by srebling** [comment]
package.json attached...

**Comment by jyapayne** [comment]
I didn't get the attachment :0

**Comment by srebling** [comment]
On Nov 04, 2015, at 01:28 PM, Joey <notifications@github.com> wrote:

I didn't get the attachment :0

**Comment by jyapayne** [comment]
You probably have to attach it directly in github, not via email.

**Comment by jyapayne** [comment]
Thanks, I got the package.json. Do you have app.js referenced from your index.html file? If so, you do not need the "Node Main" field filled out. This will cause issues. If you don't have the app.js referenced in the index.html, then you should reference it there and take it out of the node main field. Let me know if this helps :)

**Comment by srebling** [comment]
That helped somewhat.  Now index.html is displayed when I run that app.  But I don't think my code in app.js is running.  Normally I run 'node app' from the command line then browse to localhost to view the app.  How do I get the app.js code to run?  Seems like I need to reference app.js as Node Main in web2exe but that doesn't allow it run at all.

**Comment by jyapayne** [comment]
You need to include it in your index.html file by using a script tag. Also, if you have a main function, you'll want to call it right after your include. Since NW.js has node.js built in, all of the node.js functionality is built in on the "client" side.

For example:
```html
<script src="app.js"></script>
<script type="text/javascript">
  mainNodejsFunction();
</script>
```

**Comment by jyapayne** [comment]
Although, you might be able to run the app.js using the node main section if your app.js is to be treated like a daemon/background process. See [here](https://github.com/nwjs/nw.js/wiki/node-main) for an example.

**Comment by srebling** [comment]
I definitely need the background process.  app.js has code that needs to run only once on start up.  Have not been able to get it working yet based on example.  The html views work but I can not get the background code to run.  Will continue to try/research.

**Comment by jyapayne** [comment]
So did the issue turn out to be the path that shelljs uses?

**Comment by srebling** [comment]
Yes, that was it, but I don't quite understand it yet.  The culprit is the fqdn node module which is a dependency of another node module in my project.  Apparently it wasn't being used because I simple removed the fqdn folder and everything worked with no errors.  That's not the longterm fix, but it did prove Web2Exe works!

**Comment by jyapayne** [comment]
Cool :) I'll mark this issue as solved for now.
