### ISSUE TITLE
Request: can choose "hide system files" in export settings

### ISSUE THREAD

**Issue by Inateno** [jyapayne/Web2Executable#93]
Hello,

I'm using this tools since a while now, BTW nice job.
It would be nice to put a checkbox in the export settings window to allow us to hide by default all files/folders inside the output excepted the "myApp.exe" file.

I create applications for basic users and I deliver applications without installer.
If they only see the main exe file as visible it's better (ofc they can show other files, but lot of users don't. And even if they do, they'll see files as hidden so that's okay).

Maybe there is permissions restriction. I'm not sure because I do manual "hide files" actually and it works well.

Thanks

**Comment by jyapayne** [comment]
Thank you :)

Even though I don't condone hiding necessary files from the user (in case they decide to copy them elsewhere), I could create an option that allows a custom script to be ran after exporting is done. This way, you could accomplish what you need by writing a batch script that could be run that adds the hidden attribute to all the files except the exe. Would that work for you?

**Comment by Inateno** [comment]
That's okay too. Actually I run a bash manually so that's almsot the same, but yeah!
And I think running a custom script when export end is nice for everyone.

Maybe add in our package.json a list of script to run after.

**Comment by jyapayne** [comment]
I've added the ability to run Python, bat, and bash scripts to the export tab :) Let me know if this is good for you :) There are some pre-filled variables that you can access (I will be documenting these soon, but they are somewhat self-explanatory):

For a project called "Cargo" with an output folder selected as "output" and only "Windows x32" selected in the export options:

```bash
PROJECT_DIR='C:\Users\Joey\Downloads\Cargo'
PROJECT_NAME='Cargo'
EXPORT_DIR='C:\Users\Joey\Downloads\Cargo\output\Cargo'
EXPORT_DIRS[0]='C:\Users\Joey\Downloads\Cargo\output\Cargo\windows-x32'
MAC64_EXPORT_DIR=''
MAC32_EXPORT_DIR=''
WIN64_EXPORT_DIR=''
WIN32_EXPORT_DIR='C:\Users\Joey\Downloads\Cargo\output\Cargo\windows-x32'
LINUX64_EXPORT_DIR=''
LINUX32_EXPORT_DIR=''
NUM_DIRS=1
```

**Comment by Inateno** [comment]
Awesome, I read the run_script function this is perfect. A must have !

Next time I'll try to deep inside and PR :)

**Comment by jyapayne** [comment]
Cool, sounds good :)
