### ISSUE TITLE
Icons not showing in v0.3.0b

### ISSUE THREAD

**Issue by 2braincells2go** [jyapayne/Web2Executable#97]
Hi Joey, top of the day to you.

Just downloaded v0.3.0b win (no installer version) and testing on Win 10.

Working great and very smooth. But the PNG icons I choose for win, exe and mac are not being shown in icon boxes. They do appear when compiled software started but not showing in little icon windows within Web2Exe. The area where preview of icons is totally blank for all three.

Certainly not a show stopper but thought you may like to know.

Thanks once again for your hard work on this software!

Woody

**Comment by jyapayne** [comment]
Thanks for letting me know, Woody :) There's been a few issues around paths lately and this appears to be one of the effects. I'll have it fixed shortly :)

**Comment by jyapayne** [comment]
Okay, should be all good in 0.3.1b :)

**Comment by 2braincells2go** [comment]
Thanks you sir! Will give it a try that afternoon.
